import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Notebook 6.2: Phân loại Đa phương thức (WSI + Genomics RNA-Seq)\n",
    "**Mục tiêu:** Kích hoạt \"God Mode\" bằng cách kết hợp đặc trưng hình thái tế bào (WSI) với bản đồ gen phân tử (RNA-Seq Expression).\n",
    "\n",
    "**Vấn đề:** File RNA-Seq chứa đến 20,500 gen, cực kỳ nặng và dễ gây Overfitting.\n",
    "**Giải pháp:** Áp dụng thuật toán **Variance Threshold** (Lọc phương sai) để tự động trích xuất 500 gen biến động mạnh nhất (những gen mang tính quyết định số phận tế bào), sau đó đẩy vào mạng nơ-ron để hợp nhất với ảnh."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install nystrom-attention"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.feature_selection import VarianceThreshold\n",
    "from sklearn.metrics import accuracy_score, f1_score\n",
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "from nystrom_attention import NystromAttention\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1. Nén Dữ Liệu Gen (RNA-Seq) bằng Variance Threshold"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "PT_DIR = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca-resnet50-wsi-features/pt_files' \n",
    "RNASEQ_FILE = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca/data_mrna_seq_v2_rsem.txt'\n",
    "CLINICAL_CSV = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca/tcga_brca_master_matched_cohort.csv'\n",
    "\n",
    "print(\"Đang xử lý 20,500 gen từ file RNA-Seq...\")\n",
    "rna_df = pd.read_csv(RNASEQ_FILE, sep='\\t')\n",
    "if 'Entrez_Gene_Id' in rna_df.columns:\n",
    "    rna_df = rna_df.drop(columns=['Entrez_Gene_Id'])\n",
    "\n",
    "# Chuyển vị ma trận: Hàng là Bệnh nhân, Cột là Gen\n",
    "rna_df = rna_df.set_index('Hugo_Symbol').T\n",
    "\n",
    "# Cắt bỏ đuôi suffix (VD: TCGA-BH-A0GZ-01 -> TCGA-BH-A0GZ)\n",
    "rna_df.index = rna_df.index.str[:12]\n",
    "rna_df = rna_df[~rna_df.index.duplicated(keep='first')]\n",
    "rna_df = rna_df.dropna(axis=1)\n",
    "\n",
    "# Thuật toán Variance Threshold: Chọn 500 gen biến động cao nhất\n",
    "variances = rna_df.var()\n",
    "top_500_genes = variances.nlargest(500).index\n",
    "rna_500 = rna_df[top_500_genes]\n",
    "\n",
    "# Chuẩn hóa dữ liệu gen\n",
    "scaler = StandardScaler()\n",
    "rna_500_scaled = pd.DataFrame(scaler.fit_transform(rna_500), index=rna_500.index)\n",
    "print(f\"Đã nén thành công RNA-Seq xuống còn {rna_500_scaled.shape[1]} gen!\")\n",
    "\n",
    "df_clin = pd.read_csv(CLINICAL_CSV, sep='\\t')\n",
    "if len(df_clin.columns) < 5:\n",
    "    df_clin = pd.read_csv(CLINICAL_CSV)\n",
    "valid_subtypes = ['BRCA_LumA', 'BRCA_LumB', 'BRCA_Basal', 'BRCA_Her2']\n",
    "df_clin = df_clin[df_clin['pam50_subtype'].isin(valid_subtypes)].copy()\n",
    "label_map = {'BRCA_LumA': 0, 'BRCA_LumB': 1, 'BRCA_Basal': 2, 'BRCA_Her2': 3}\n",
    "df_clin['label'] = df_clin['pam50_subtype'].map(label_map)\n",
    "label_dict = dict(zip(df_clin['patientId'], df_clin['label']))\n",
    "\n",
    "# Tìm các bệnh nhân có đủ cả 3: Ảnh + Nhãn + Gen\n",
    "valid_pids = []\n",
    "for pid in label_dict.keys():\n",
    "    if pid in rna_500_scaled.index and os.path.exists(os.path.join(PT_DIR, f\"{pid}.pt\")):\n",
    "        valid_pids.append(pid)\n",
    "labels = [label_dict[pid] for pid in valid_pids]\n",
    "print(f\"Tổng số bệnh nhân hợp lệ (Đa phương thức): {len(valid_pids)}\")\n",
    "\n",
    "class GenomicsDataset(Dataset):\n",
    "    def __init__(self, pids, pt_dir, rna_data, label_map):\n",
    "        self.pids = pids\n",
    "        self.pt_dir = pt_dir\n",
    "        self.rna_data = rna_data\n",
    "        self.label_map = label_map\n",
    "        \n",
    "    def __len__(self):\n",
    "        return len(self.pids)\n",
    "        \n",
    "    def __getitem__(self, idx):\n",
    "        pid = self.pids[idx]\n",
    "        img = torch.load(os.path.join(self.pt_dir, f\"{pid}.pt\"), map_location='cpu')\n",
    "        genomics = torch.tensor(self.rna_data.loc[pid].values, dtype=torch.float32)\n",
    "        label = self.label_map[pid]\n",
    "        return img, genomics, label, pid"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2. Kiến Trúc Mạng Hợp Nhất (WSI + RNA-Seq)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class TransLayer(nn.Module):\n",
    "    def __init__(self, norm_layer=nn.LayerNorm, dim=512):\n",
    "        super().__init__()\n",
    "        self.norm = norm_layer(dim)\n",
    "        self.attn = NystromAttention(dim=dim, dim_head=dim//8, heads=8, num_landmarks=dim//2, pinv_iterations=6, residual=True, dropout=0.1)\n",
    "    def forward(self, x):\n",
    "        return x + self.attn(self.norm(x))\n",
    "\n",
    "class TransMIL_Vision_Extractor(nn.Module):\n",
    "    def __init__(self, input_dim=2048, out_dim=512):\n",
    "        super().__init__()\n",
    "        self._fc1 = nn.Sequential(nn.Linear(input_dim, 512), nn.ReLU())\n",
    "        self.cls_token = nn.Parameter(torch.randn(1, 1, 512))\n",
    "        self.layer1 = TransLayer(dim=512)\n",
    "        self.layer2 = TransLayer(dim=512)\n",
    "        self.norm = nn.LayerNorm(512)\n",
    "        \n",
    "    def forward(self, x):\n",
    "        h = self._fc1(x.float())\n",
    "        cls_tokens = self.cls_token.expand(h.shape[0], -1, -1)\n",
    "        h = torch.cat((cls_tokens, h), dim=1)\n",
    "        h = self.layer1(h)\n",
    "        h = self.layer2(h)\n",
    "        return self.norm(h)[:,0]\n",
    "\n",
    "class Multimodal_GenomicsFusion(nn.Module):\n",
    "    def __init__(self, genomics_dim=500, num_classes=4):\n",
    "        super().__init__()\n",
    "        self.vision_net = TransMIL_Vision_Extractor()\n",
    "        \n",
    "        # Mạng Genomics MLP mạnh mẽ hơn để xử lý 500 gen\n",
    "        self.genomics_net = nn.Sequential(\n",
    "            nn.Linear(genomics_dim, 256),\n",
    "            nn.BatchNorm1d(256),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(256, 512),\n",
    "            nn.ReLU()\n",
    "        )\n",
    "        \n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.Linear(512 + 512, 256),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(256, num_classes)\n",
    "        )\n",
    "        \n",
    "    def forward(self, img_feat, gen_feat):\n",
    "        v_img = self.vision_net(img_feat)\n",
    "        v_gen = self.genomics_net(gen_feat)\n",
    "        v_fusion = torch.cat((v_img, v_gen), dim=1)\n",
    "        return self.classifier(v_fusion)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3. Huấn luyện (RAdam + Accumulation)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(valid_pids) > 0:\n",
    "    class_weights = compute_class_weight('balanced', classes=np.unique(labels), y=labels)\n",
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "    class_weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)\n",
    "    criterion = nn.CrossEntropyLoss(weight=class_weights_tensor, label_smoothing=0.1)\n",
    "    \n",
    "    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
    "    epochs, batch_size, accumulation_steps = 30, 1, 16\n",
    "    fold_results = []\n",
    "\n",
    "    for fold, (train_idx, test_idx) in enumerate(skf.split(valid_pids, labels)):\n",
    "        print(f\"\\n--- [Multimodal WSI+Genomics] Fold {fold + 1}/5 ---\")\n",
    "        train_pids = [valid_pids[i] for i in train_idx]\n",
    "        test_pids = [valid_pids[i] for i in test_idx]\n",
    "        \n",
    "        train_dataset = GenomicsDataset(train_pids, PT_DIR, rna_500_scaled, label_dict)\n",
    "        test_dataset = GenomicsDataset(test_pids, PT_DIR, rna_500_scaled, label_dict)\n",
    "        \n",
    "        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)\n",
    "        test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)\n",
    "        \n",
    "        model = Multimodal_GenomicsFusion().to(device)\n",
    "        optimizer = optim.RAdam(model.parameters(), lr=5e-4, weight_decay=1e-5)\n",
    "        scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-6)\n",
    "        \n",
    "        best_f1, best_acc = 0.0, 0.0\n",
    "        \n",
    "        for epoch in range(epochs):\n",
    "            model.train()\n",
    "            optimizer.zero_grad()\n",
    "            \n",
    "            for step, (img, gen, label, _) in enumerate(train_loader):\n",
    "                img, gen, label = img.to(device), gen.to(device), label.to(device)\n",
    "                logits = model(img, gen)\n",
    "                loss = criterion(logits, label) / accumulation_steps\n",
    "                loss.backward()\n",
    "                \n",
    "                if (step + 1) % accumulation_steps == 0 or (step + 1) == len(train_loader):\n",
    "                    optimizer.step()\n",
    "                    optimizer.zero_grad()\n",
    "            \n",
    "            scheduler.step()\n",
    "            model.eval()\n",
    "            preds, tgts = [], []\n",
    "            with torch.no_grad():\n",
    "                for img, gen, label, _ in test_loader:\n",
    "                    img, gen = img.to(device), gen.to(device)\n",
    "                    logits = model(img, gen)\n",
    "                    preds.extend(torch.argmax(logits, 1).cpu().numpy())\n",
    "                    tgts.extend(label.numpy())\n",
    "            \n",
    "            val_f1 = f1_score(tgts, preds, average='macro')\n",
    "            if val_f1 > best_f1:\n",
    "                best_f1, best_acc = val_f1, accuracy_score(tgts, preds)\n",
    "                \n",
    "        print(f\"Fold {fold+1} Kỷ lục: Accuracy: {best_acc:.4f} | Macro-F1: {best_f1:.4f}\")\n",
    "        fold_results.append((best_acc, best_f1))\n",
    "\n",
    "    print(\"\\n=======================================================\")\n",
    "    print(f\"TỔNG KẾT MULTIMODAL WSI + GENOMICS (GOD MODE) (5-FOLD)\")\n",
    "    print(f\"🎯 Accuracy: {np.mean([x[0] for x in fold_results]):.4f}\")\n",
    "    print(f\"⚖️ Macro-F1: {np.mean([x[1] for x in fold_results]):.4f}\")\n",
    "    print(\"=======================================================\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

out_path = r'C:\Users\huynh\Desktop\breast cancer\06.2_Multimodal_WSI_Genomics.ipynb'
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)
