import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Kế Hoạch Thực Tập: AI Y Tế Đa Phương Thức (9 Notebooks Pipeline)\n",
    "## Notebook 5: Siêu mô hình TransMIL (SOTA Deep Learning - Official Architecture)\n",
    "\n",
    "**Sự trỗi dậy của Mạng Nơ-ron Chú ý (Attention) và Không gian 2D:**\n",
    "Sau thất bại thảm hại của cả Machine Learning Truyền thống (Notebook 3) và Neural Network Tiêu chuẩn (Notebook 4), chúng ta đã chứng minh được: **Kỹ thuật ép dẹp trung bình (Mean-Pooling) là kẻ thù số một của dữ liệu Y tế WSI.**\n",
    "\n",
    "Trong Notebook này, chúng ta sẽ triển khai nguyên bản kiến trúc **TransMIL (Shao et al., NeurIPS 2021)** - kiến trúc State-of-the-Art (SOTA) mạnh nhất hiện nay trong phân tích bệnh học kỹ thuật số. So với bản Hybrid tự build, bản gốc này sở hữu 3 vũ khí hủy diệt:\n",
    "\n",
    "1. **Nyströmformer ($O(n)$):** Thay vì Standard Transformer bị quá tải với 5000 mảnh tế bào, thuật toán xấp xỉ Nyström giúp mô hình học mượt mà hàng vạn mảnh tế bào cùng lúc mà không bị tràn RAM.\n",
    "2. **PPEG (Pyramid Position Encoding Generator):** Module CNN độc quyền giúp tái tạo lại tọa độ không gian 2D cho các tế bào. Mạng AI sẽ nhận thức được tế bào số 1 và số 2 đang nằm cạnh nhau, giúp nó phát hiện khối u mọc thành cụm.\n",
    "3. **[CLS] Token Aggregation:** Nó không dùng hàm `Tanh` lỗi thời, mà tung vào chuỗi tế bào một biến gián điệp `[CLS]`. Biến này đi qua toàn bộ mạng, liên tục nghe ngóng và thu thập tín hiệu ung thư HER2 từ các mảnh tế bào khác, cuối cùng gom lại thành 1 siêu vector chứa toàn thông tin tử huyệt."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cài đặt thư viện Nyströmformer bắt buộc cho TransMIL\n",
    "!pip install nystrom-attention"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from tqdm import tqdm\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "import torch.nn.functional as F\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay\n",
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "from nystrom_attention import NystromAttention\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1. Chuẩn Bị Dữ Liệu: Bag of Features\n",
    "DataLoader không gộp trung bình mà load nguyên khối ma trận `[N, 2048]` của từng bệnh nhân."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "PT_DIR = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca-resnet50-wsi-features/pt_files' \n",
    "CLINICAL_CSV = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca/tcga_brca_master_matched_cohort.csv'\n",
    "\n",
    "df = pd.read_csv(CLINICAL_CSV, sep='\\t')\n",
    "if len(df.columns) < 5:\n",
    "    df = pd.read_csv(CLINICAL_CSV)\n",
    "\n",
    "valid_subtypes = ['BRCA_LumA', 'BRCA_LumB', 'BRCA_Basal', 'BRCA_Her2']\n",
    "df_filtered = df[df['pam50_subtype'].isin(valid_subtypes)].copy()\n",
    "label_map = {'BRCA_LumA': 0, 'BRCA_LumB': 1, 'BRCA_Basal': 2, 'BRCA_Her2': 3}\n",
    "df_filtered['label'] = df_filtered['pam50_subtype'].map(label_map)\n",
    "patient_label_dict = dict(zip(df_filtered['patientId'], df_filtered['label']))\n",
    "\n",
    "class MILBagDataset(Dataset):\n",
    "    def __init__(self, patient_ids, pt_dir, label_dict):\n",
    "        self.patient_ids = patient_ids\n",
    "        self.pt_dir = pt_dir\n",
    "        self.label_dict = label_dict\n",
    "        \n",
    "    def __len__(self):\n",
    "        return len(self.patient_ids)\n",
    "        \n",
    "    def __getitem__(self, idx):\n",
    "        pid = self.patient_ids[idx]\n",
    "        pt_path = os.path.join(self.pt_dir, f\"{pid}.pt\")\n",
    "        features = torch.load(pt_path, map_location='cpu') # Shape: [N, 2048]\n",
    "        label = self.label_dict[pid]\n",
    "        return features, label, pid\n",
    "\n",
    "if os.path.exists(PT_DIR):\n",
    "    valid_pids = [p for p in df_filtered['patientId'].tolist() if os.path.exists(os.path.join(PT_DIR, f\"{p}.pt\"))]\n",
    "    labels = [patient_label_dict[pid] for pid in valid_pids]\n",
    "    print(f\"Tìm thấy {len(valid_pids)} bệnh nhân hợp lệ.\")\n",
    "else:\n",
    "    print(\"Lỗi: Không tìm thấy thư mục PT_DIR.\")\n",
    "    valid_pids, labels = [], []"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2. Thiết Kế Kiến Trúc TransMIL Gốc (Original Official Architecture)\n",
    "Mã nguồn được tham khảo chuẩn hóa từ bài báo gốc NeurIPS 2021."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class TransLayer(nn.Module):\n",
    "    def __init__(self, norm_layer=nn.LayerNorm, dim=512):\n",
    "        super().__init__()\n",
    "        self.norm = norm_layer(dim)\n",
    "        self.attn = NystromAttention(\n",
    "            dim = dim,\n",
    "            dim_head = dim//8,\n",
    "            heads = 8,\n",
    "            num_landmarks = dim//2,    \n",
    "            pinv_iterations = 6,    \n",
    "            residual = True,         \n",
    "            dropout=0.1\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = x + self.attn(self.norm(x))\n",
    "        return x\n",
    "\n",
    "class PPEG(nn.Module):\n",
    "    \"\"\"\n",
    "    Pyramid Position Encoding Generator (PPEG)\n",
    "    Dùng mạng CNN 2D (Conv2d 3, 5, 7) để tái tạo bản đồ tọa độ tế bào giả lập.\n",
    "    \"\"\"\n",
    "    def __init__(self, dim=512):\n",
    "        super(PPEG, self).__init__()\n",
    "        self.proj = nn.Conv2d(dim, dim, 7, 1, 7//2, groups=dim)\n",
    "        self.proj1 = nn.Conv2d(dim, dim, 5, 1, 5//2, groups=dim)\n",
    "        self.proj2 = nn.Conv2d(dim, dim, 3, 1, 3//2, groups=dim)\n",
    "\n",
    "    def forward(self, x, H, W):\n",
    "        B, _, C = x.shape\n",
    "        cls_token, feat_token = x[:, 0], x[:, 1:]\n",
    "        cnn_feat = feat_token.transpose(1, 2).view(B, C, H, W)\n",
    "        x = self.proj(cnn_feat) + cnn_feat + self.proj1(cnn_feat) + self.proj2(cnn_feat)\n",
    "        x = x.flatten(2).transpose(1, 2)\n",
    "        x = torch.cat((cls_token.unsqueeze(1), x), dim=1)\n",
    "        return x\n",
    "\n",
    "class TransMIL(nn.Module):\n",
    "    def __init__(self, input_dim=2048, n_classes=4):\n",
    "        super(TransMIL, self).__init__()\n",
    "        self.pos_layer = PPEG(dim=512)\n",
    "        # Nén từ 2048 chiều (ResNet50) xuống 512 chiều\n",
    "        self._fc1 = nn.Sequential(nn.Linear(input_dim, 512), nn.ReLU())\n",
    "        self.cls_token = nn.Parameter(torch.randn(1, 1, 512))\n",
    "        self.n_classes = n_classes\n",
    "        self.layer1 = TransLayer(dim=512)\n",
    "        self.layer2 = TransLayer(dim=512)\n",
    "        self.norm = nn.LayerNorm(512)\n",
    "        self._fc2 = nn.Linear(512, self.n_classes)\n",
    "\n",
    "    def forward(self, x):\n",
    "        # x có shape: [1, N, 2048]\n",
    "        h = x.float()\n",
    "        h = self._fc1(h) # [1, N, 512]\n",
    "        \n",
    "        # ----> Pad sequence thành hình vuông để dùng CNN 2D cho vị trí (PPEG)\n",
    "        H = h.shape[1]\n",
    "        _H, _W = int(np.ceil(np.sqrt(H))), int(np.ceil(np.sqrt(H)))\n",
    "        add_length = _H * _W - H\n",
    "        h = torch.cat([h, h[:,:add_length,:]], dim = 1) # [1, _H*_W, 512]\n",
    "\n",
    "        # ----> Thêm gián điệp [CLS] Token\n",
    "        B = h.shape[0]\n",
    "        cls_tokens = self.cls_token.expand(B, -1, -1) # B=1\n",
    "        h = torch.cat((cls_tokens, h), dim=1) # [1, _H*_W + 1, 512]\n",
    "\n",
    "        # ----> Nyström Attention Layer 1\n",
    "        h = self.layer1(h) \n",
    "\n",
    "        # ----> Bơm thông tin tọa độ không gian 2D bằng PPEG\n",
    "        h = self.pos_layer(h, _H, _W) \n",
    "        \n",
    "        # ----> Nyström Attention Layer 2\n",
    "        h = self.layer2(h) \n",
    "\n",
    "        # ----> Gom kết quả: Chỉ rút thẻ [CLS] ra để chốt phân loại\n",
    "        h = self.norm(h)[:,0]\n",
    "\n",
    "        # ----> Phân loại cuối cùng\n",
    "        logits = self._fc2(h) # [1, 4]\n",
    "        return logits, None # TransMIL nguyên bản không xuất ma trận A rõ ràng như ABMIL, nên trả về None"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3. Huấn Luyện SOTA (Stratified 5-Fold)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(valid_pids) > 0:\n",
    "    class_weights = compute_class_weight('balanced', classes=np.unique(labels), y=labels)\n",
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "    class_weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)\n",
    "    criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)\n",
    "    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
    "    \n",
    "    epochs = 20\n",
    "    batch_size = 1 # Bắt buộc vì WSI có độ dài biến thiên\n",
    "    \n",
    "    fold_results = []\n",
    "    best_global_preds = []\n",
    "    best_global_labels = []\n",
    "\n",
    "    print(f\"Khởi động lò nung SOTA TransMIL (Official) trên thiết bị: {device}\")\n",
    "    \n",
    "    for fold, (train_idx, test_idx) in enumerate(skf.split(valid_pids, labels)):\n",
    "        print(f\"\\n--- [TransMIL Official] Bắt đầu Fold {fold + 1}/5 ---\")\n",
    "        \n",
    "        train_pids = [valid_pids[i] for i in train_idx]\n",
    "        test_pids = [valid_pids[i] for i in test_idx]\n",
    "        \n",
    "        train_dataset = MILBagDataset(train_pids, PT_DIR, patient_label_dict)\n",
    "        test_dataset = MILBagDataset(test_pids, PT_DIR, patient_label_dict)\n",
    "        \n",
    "        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)\n",
    "        test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)\n",
    "        \n",
    "        model = TransMIL(input_dim=2048, n_classes=4).to(device)\n",
    "        optimizer = optim.Adam(model.parameters(), lr=2e-4, weight_decay=1e-5)\n",
    "        \n",
    "        best_f1 = 0.0\n",
    "        best_acc = 0.0\n",
    "        fold_preds = []\n",
    "        fold_labels = []\n",
    "        \n",
    "        for epoch in range(epochs):\n",
    "            model.train()\n",
    "            for features, label, _ in train_loader:\n",
    "                features, label = features.to(device), label.to(device)\n",
    "                \n",
    "                # Vì Batch=1, features có shape [1, N, 2048]\n",
    "                optimizer.zero_grad()\n",
    "                logits, _ = model(features)\n",
    "                loss = criterion(logits, label)\n",
    "                loss.backward()\n",
    "                optimizer.step()\n",
    "            \n",
    "            model.eval()\n",
    "            epoch_preds = []\n",
    "            epoch_labels = []\n",
    "            with torch.no_grad():\n",
    "                for features, label, _ in test_loader:\n",
    "                    features, label = features.to(device), label.to(device)\n",
    "                    logits, _ = model(features)\n",
    "                    _, pred = torch.max(logits, 1)\n",
    "                    epoch_preds.extend(pred.cpu().numpy())\n",
    "                    epoch_labels.extend(label.cpu().numpy())\n",
    "            \n",
    "            val_acc = accuracy_score(epoch_labels, epoch_preds)\n",
    "            val_f1 = f1_score(epoch_labels, epoch_preds, average='macro')\n",
    "            \n",
    "            if val_f1 > best_f1:\n",
    "                best_f1 = val_f1\n",
    "                best_acc = val_acc\n",
    "                fold_preds = epoch_preds\n",
    "                fold_labels = epoch_labels\n",
    "                \n",
    "        print(f\"Fold {fold+1} Kỷ lục mới - Accuracy: {best_acc:.4f} | Macro-F1: {best_f1:.4f}\")\n",
    "        fold_results.append((best_acc, best_f1))\n",
    "        best_global_preds.extend(fold_preds)\n",
    "        best_global_labels.extend(fold_labels)\n",
    "    \n",
    "    mean_acc = np.mean([x[0] for x in fold_results])\n",
    "    std_acc = np.std([x[0] for x in fold_results])\n",
    "    mean_f1 = np.mean([x[1] for x in fold_results])\n",
    "    std_f1 = np.std([x[1] for x in fold_results])\n",
    "    \n",
    "    print(\"\\n=======================================================\")\n",
    "    print(\" TỔNG KẾT TRANSMIL SOTA OFFICIAL (5-FOLD CROSS VALIDATION)\")\n",
    "    print(\"=======================================================\")\n",
    "    print(f\"🎯 Khai tử giới hạn truyền thống! Accuracy: {mean_acc:.4f} ˙ {std_acc:.4f}\")\n",
    "    print(f\"⚖️ Chinh phục tầm cao mới: Macro-F1: {mean_f1:.4f} ˙ {std_f1:.4f}\")\n",
    "    print(\"=======================================================\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 4. Bằng Chứng Sức Mạnh: Confusion Matrix\n",
    "Bạn sẽ thấy số lượng ca đoán trúng nằm ở đường chéo chính yếu tăng vọt. Đặc biệt là nhóm ung thư HER2 và Basal không còn bị mô hình lãng quên!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(valid_pids) > 0:\n",
    "    cm = confusion_matrix(best_global_labels, best_global_preds)\n",
    "    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['LumA', 'LumB', 'Basal', 'HER2'])\n",
    "    \n",
    "    fig, ax = plt.subplots(figsize=(8, 6))\n",
    "    disp.plot(cmap='viridis', ax=ax, values_format='d') \n",
    "    plt.title('Bản đồ Bứt phá - TransMIL Official Confusion Matrix', fontsize=14, fontweight='bold')\n",
    "    plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

out_path = r'C:\Users\huynh\Desktop\breast cancer\05_Classification_TransMIL_SOTA.ipynb'
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)

print("Created Notebook 5 TransMIL Official successfully.")
