import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Kế Hoạch Thực Tập: AI Y Tế Đa Phương Thức (9 Notebooks Pipeline)\n",
    "## Notebook 5: Siêu mô hình TransMIL (SOTA Deep Learning)\n",
    "\n",
    "**Sự trỗi dậy của Self-Attention (Sự chú ý tự thân):**\n",
    "Sau thất bại thảm hại của cả Machine Learning Truyền thống (Notebook 3) và Neural Network Tiêu chuẩn (Notebook 4), chúng ta đã chứng minh được: **Kỹ thuật ép dẹp trung bình (Mean-Pooling) là kẻ thù số một của dữ liệu Y tế WSI.**\n",
    "\n",
    "Trong Notebook này, chúng ta sẽ triển khai **TransMIL (Transformer-based Multiple Instance Learning)** - kiến trúc State-of-the-Art (SOTA) mạnh nhất hiện nay trong phân tích bệnh học kỹ thuật số. \n",
    "\n",
    "**Quy trình khác biệt của TransMIL:**\n",
    "1. **Bảo toàn Số lượng:** Bệnh nhân có 5000 mảnh tế bào? TransMIL sẽ đọc cả 5000 mảnh riêng biệt, không cộng trung bình.\n",
    "2. **Cơ chế Self-Attention:** Nó sẽ tự động quét qua 5000 mảnh này, tìm xem mảnh nào có dấu hiệu ung thư và **gán Trọng số cực lớn (Attention Score = 0.99)**, trong khi bỏ qua các mô mỡ vô hại (gán điểm 0.01). \n",
    "3. **Gộp có chọn lọc:** Cuối cùng, nó mới gộp 5000 mảnh lại với nhau, nhưng gộp theo Trọng số Attention (Mảnh nào điểm cao thì được ưu tiên). Tín hiệu ung thư HER2 sẽ được bảo vệ tuyệt đối!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from tqdm import tqdm\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "import torch.nn.functional as F\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay\n",
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1. Chuẩn Bị Dữ Liệu: Bag of Features (Giữ nguyên cấu trúc nguyên bản)\n",
    "Khác với các Notebook trước, lần này DataLoader sẽ load nguyên khối ma trận `[N, 2048]` (Với N là số lượng mảnh tế bào ngẫu nhiên của từng bệnh nhân, N có thể là vài trăm đến vài ngàn)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "PT_DIR = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca-resnet50-wsi-features/pt_files' \n",
    "CLINICAL_CSV = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca/tcga_brca_master_matched_cohort.csv'\n",
    "\n",
    "df = pd.read_csv(CLINICAL_CSV, sep='\\t')\n",
    "if len(df.columns) < 5:\n",
    "    df = pd.read_csv(CLINICAL_CSV)\n",
    "\n",
    "valid_subtypes = ['BRCA_LumA', 'BRCA_LumB', 'BRCA_Basal', 'BRCA_Her2']\n",
    "df_filtered = df[df['pam50_subtype'].isin(valid_subtypes)].copy()\n",
    "label_map = {'BRCA_LumA': 0, 'BRCA_LumB': 1, 'BRCA_Basal': 2, 'BRCA_Her2': 3}\n",
    "df_filtered['label'] = df_filtered['pam50_subtype'].map(label_map)\n",
    "patient_label_dict = dict(zip(df_filtered['patientId'], df_filtered['label']))\n",
    "\n",
    "class MILBagDataset(Dataset):\n",
    "    \"\"\"\n",
    "    Dataset đặc biệt cho bài toán MIL. \n",
    "    Thay vì trả về 1 vector, nó trả về toàn bộ Ma trận [N, 2048] của bệnh nhân.\n",
    "    \"\"\"\n",
    "    def __init__(self, patient_ids, pt_dir, label_dict):\n",
    "        self.patient_ids = patient_ids\n",
    "        self.pt_dir = pt_dir\n",
    "        self.label_dict = label_dict\n",
    "        \n",
    "    def __len__(self):\n",
    "        return len(self.patient_ids)\n",
    "        \n",
    "    def __getitem__(self, idx):\n",
    "        pid = self.patient_ids[idx]\n",
    "        pt_path = os.path.join(self.pt_dir, f\"{pid}.pt\")\n",
    "        \n",
    "        # Load toàn bộ N mảnh ảnh (Ví dụ: N=5000)\n",
    "        features = torch.load(pt_path, map_location='cpu') # Shape: [N, 2048]\n",
    "        label = self.label_dict[pid]\n",
    "        \n",
    "        return features, label, pid\n",
    "\n",
    "# Kiểm tra file hợp lệ\n",
    "if os.path.exists(PT_DIR):\n",
    "    valid_pids = [p for p in df_filtered['patientId'].tolist() if os.path.exists(os.path.join(PT_DIR, f\"{p}.pt\"))]\n",
    "    labels = [patient_label_dict[pid] for pid in valid_pids]\n",
    "    print(f\"Tìm thấy {len(valid_pids)} bệnh nhân hợp lệ.\")\n",
    "else:\n",
    "    print(\"Lỗi: Không tìm thấy thư mục PT_DIR.\")\n",
    "    valid_pids, labels = [], []"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2. Thiết Kế Lõi Mô Hình TransMIL (Giải thích Chi Tiết Từng Lớp)\n",
    "\n",
    "Đoạn code dưới đây là \"Trái tim\" của toàn bộ Đồ án. Đây là lúc thể hiện trình độ Deep Learning của bạn trước hội đồng.\n",
    "\n",
    "**1. Lớp Nén Đặc Trưng (Compressor):** Đầu vào là ma trận `[N, 2048]`. Lớp `Linear` đầu tiên sẽ nén 2048 chiều khổng lồ xuống còn `512` chiều để tiết kiệm RAM mà vẫn giữ đặc trưng cốt lõi.\n",
    "**2. Lớp Transformer Encoder:** Đây là lớp áp dụng cơ chế `Self-Attention`. Các mảnh tế bào sẽ \"Nói chuyện\" với nhau. Mảnh tế bào góc trái sẽ tương tác với mảnh ở góc phải để xem chúng có mối liên hệ cấu trúc nào không (Ví dụ: khối u thường mọc thành cụm).\n",
    "**3. Khối Attention MIL (ABMIL - Attention-based MIL):** Đây là phần quan trọng nhất! Khối này có nhiệm vụ chốt lại một **Điểm số từ 0 đến 1** cho mỗi mảnh tế bào. Công thức kinh điển `Tanh() * Sigmoid()` giúp mô hình lọc nhiễu cực tốt.\n",
    "**4. Lớp Phân loại (Classifier):** Sau khi tính được trung bình có trọng số (Nhân ma trận đặc trưng với điểm Attention), ta thu được 1 siêu vector đại diện cho bệnh nhân. Vector này đi qua lớp Linear cuối cùng để chọn ra 1 trong 4 nhãn ung thư."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class TransMIL(nn.Module):\n",
    "    def __init__(self, input_dim=2048, hidden_dim=512, num_classes=4):\n",
    "        super(TransMIL, self).__init__()\n",
    "        \n",
    "        # 1. BƯỚC NÉN (Compressor)\n",
    "        # Chuyển vector từ 2048 chiều xuống 512 chiều\n",
    "        self.fc1 = nn.Sequential(\n",
    "            nn.Linear(input_dim, hidden_dim),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3)\n",
    "        )\n",
    "        \n",
    "        # 2. KHỐI TRANSFORMER (Sự tương quan không gian)\n",
    "        # Giúp các mảnh tế bào tương tác với nhau.\n",
    "        encoder_layer = nn.TransformerEncoderLayer(d_model=hidden_dim, nhead=8, dim_feedforward=512, dropout=0.3, activation='relu')\n",
    "        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=2)\n",
    "        \n",
    "        # 3. KHỐI GIAO TRỌNG SỐ ATTENTION (Attention Mechanism)\n",
    "        # Khối này dùng để chấm điểm từng mảnh tế bào (Patch)\n",
    "        self.attention_V = nn.Sequential(\n",
    "            nn.Linear(hidden_dim, 256),\n",
    "            nn.Tanh()\n",
    "        )\n",
    "        self.attention_U = nn.Sequential(\n",
    "            nn.Linear(hidden_dim, 256),\n",
    "            nn.Sigmoid()\n",
    "        )\n",
    "        self.attention_weights = nn.Linear(256, 1)\n",
    "        \n",
    "        # 4. KHỐI PHÂN LOẠI CUỐI CÙNG (Classifier)\n",
    "        self.classifier = nn.Linear(hidden_dim, num_classes)\n",
    "        \n",
    "    def forward(self, x):\n",
    "        # x có shape: [1, N, 2048] (Batch size = 1, N mảnh tế bào)\n",
    "        x = x.squeeze(0) # Chuyển thành [N, 2048]\n",
    "        \n",
    "        # --- Bước 1: Nén đặc trưng ---\n",
    "        H = self.fc1(x)  # Shape: [N, 512]\n",
    "        \n",
    "        # --- Bước 2: Đi qua Transformer ---\n",
    "        # Transformer yêu cầu shape [N, Batch, Embed_dim], nên ta unsqueeze\n",
    "        H = H.unsqueeze(1) # [N, 1, 512]\n",
    "        H = self.transformer(H)\n",
    "        H = H.squeeze(1)   # Trả về [N, 512]\n",
    "        \n",
    "        # --- Bước 3: Chấm điểm Attention (Phép thuật nằm ở đây!) ---\n",
    "        # Tính toán A: Điểm số cho từng mảnh tế bào\n",
    "        A_V = self.attention_V(H)  # [N, 256]\n",
    "        A_U = self.attention_U(H)  # [N, 256]\n",
    "        A = self.attention_weights(A_V * A_U)  # [N, 1]\n",
    "        \n",
    "        # Dùng Softmax để chuẩn hóa các điểm số sao cho tổng = 1\n",
    "        A = torch.transpose(A, 1, 0)  # [1, N]\n",
    "        A = F.softmax(A, dim=1)       # [1, N]\n",
    "        \n",
    "        # Nhân ma trận: Điểm số (1xN) x Đặc trưng (Nx512) = Siêu Vector (1x512)\n",
    "        # Mảnh nào điểm cao (ung thư) sẽ đóng góp cực lớn vào siêu vector này!\n",
    "        M = torch.mm(A, H)  # [1, 512]\n",
    "        \n",
    "        # --- Bước 4: Phân loại ---\n",
    "        logits = self.classifier(M) # [1, 4]\n",
    "        \n",
    "        # Trả về kết quả và MA TRẬN ĐIỂM SỐ A (Để làm XAI Heatmap ở Notebook 9)\n",
    "        return logits, A"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3. Huấn luyện SOTA với Stratified 5-Fold\n",
    "**Cấu hình đặc biệt:** Mạng MIL bắt buộc phải chạy với `Batch Size = 1`. Vì mỗi bệnh nhân có số lượng mảnh tế bào khác nhau (Người có 300 mảnh, người có 5000 mảnh), ta không thể nhét chung vào một Batch được. Tính năng này ép GPU tập trung xử lý trọn vẹn từng cá thể."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(valid_pids) > 0:\n",
    "    class_weights = compute_class_weight('balanced', classes=np.unique(labels), y=labels)\n",
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "    class_weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)\n",
    "    \n",
    "    criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)\n",
    "    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
    "    \n",
    "    epochs = 15 # Transformer hội tụ khá nhanh\n",
    "    # BẮT BUỘC Batch Size = 1 cho bài toán MIL (Variable sequence length)\n",
    "    batch_size = 1 \n",
    "    \n",
    "    fold_results = []\n",
    "    best_global_preds = []\n",
    "    best_global_labels = []\n",
    "\n",
    "    print(f\"Bắt đầu Huấn luyện TransMIL SOTA trên thiết bị: {device}\")\n",
    "    \n",
    "    for fold, (train_idx, test_idx) in enumerate(skf.split(valid_pids, labels)):\n",
    "        print(f\"\\n--- [TransMIL] Bắt đầu Fold {fold + 1}/5 ---\")\n",
    "        \n",
    "        train_pids = [valid_pids[i] for i in train_idx]\n",
    "        test_pids = [valid_pids[i] for i in test_idx]\n",
    "        \n",
    "        train_dataset = MILBagDataset(train_pids, PT_DIR, patient_label_dict)\n",
    "        test_dataset = MILBagDataset(test_pids, PT_DIR, patient_label_dict)\n",
    "        \n",
    "        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)\n",
    "        test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)\n",
    "        \n",
    "        model = TransMIL().to(device)\n",
    "        # Sử dụng Learning Rate thấp vì Transformer rất nhạy cảm\n",
    "        optimizer = optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-5)\n",
    "        \n",
    "        best_f1 = 0.0\n",
    "        best_acc = 0.0\n",
    "        fold_preds = []\n",
    "        fold_labels = []\n",
    "        \n",
    "        for epoch in range(epochs):\n",
    "            model.train()\n",
    "            for features, label, _ in train_loader:\n",
    "                features, label = features.to(device), label.to(device)\n",
    "                \n",
    "                optimizer.zero_grad()\n",
    "                logits, _ = model(features)\n",
    "                loss = criterion(logits, label)\n",
    "                loss.backward()\n",
    "                optimizer.step()\n",
    "            \n",
    "            # Validation sau mỗi Epoch\n",
    "            model.eval()\n",
    "            epoch_preds = []\n",
    "            epoch_labels = []\n",
    "            with torch.no_grad():\n",
    "                for features, label, _ in test_loader:\n",
    "                    features, label = features.to(device), label.to(device)\n",
    "                    logits, _ = model(features)\n",
    "                    _, pred = torch.max(logits, 1)\n",
    "                    epoch_preds.extend(pred.cpu().numpy())\n",
    "                    epoch_labels.extend(label.cpu().numpy())\n",
    "            \n",
    "            val_acc = accuracy_score(epoch_labels, epoch_preds)\n",
    "            val_f1 = f1_score(epoch_labels, epoch_preds, average='macro')\n",
    "            \n",
    "            if val_f1 > best_f1:\n",
    "                best_f1 = val_f1\n",
    "                best_acc = val_acc\n",
    "                fold_preds = epoch_preds\n",
    "                fold_labels = epoch_labels\n",
    "                \n",
    "        print(f\"Fold {fold+1} Đỉnh cao - Accuracy: {best_acc:.4f} | Macro-F1: {best_f1:.4f}\")\n",
    "        fold_results.append((best_acc, best_f1))\n",
    "        best_global_preds.extend(fold_preds)\n",
    "        best_global_labels.extend(fold_labels)\n",
    "    \n",
    "    # Tổng kết\n",
    "    mean_acc = np.mean([x[0] for x in fold_results])\n",
    "    std_acc = np.std([x[0] for x in fold_results])\n",
    "    mean_f1 = np.mean([x[1] for x in fold_results])\n",
    "    std_f1 = np.std([x[1] for x in fold_results])\n",
    "    \n",
    "    print(\"\\n==============================================\")\n",
    "    print(\" TỔNG KẾT SIÊU MÔ HÌNH TRANSMIL SOTA (5-FOLD)\")\n",
    "    print(\"==============================================\")\n",
    "    print(f\"🎯 Khai tử giới hạn truyền thống! Accuracy: {mean_acc:.4f} ˙ {std_acc:.4f}\")\n",
    "    print(f\"⚖️ Chinh phục mốc F1: Macro-F1: {mean_f1:.4f} ˙ {std_f1:.4f}\")\n",
    "    print(\"==============================================\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 4. Bằng Chứng Chiến Thắng: Confusion Matrix\n",
    "Nếu TransMIL hoạt động đúng thiết kế, bạn sẽ thấy trên Ma trận Nhầm lẫn, các ca HER2 (Cột số 3) sẽ không còn bị lạc trôi sang cột LumA nữa. Khả năng phát hiện (Recall) của mô hình đối với các nhóm hiếm sẽ tăng vọt!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(valid_pids) > 0:\n",
    "    cm = confusion_matrix(best_global_labels, best_global_preds)\n",
    "    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['LumA', 'LumB', 'Basal', 'HER2'])\n",
    "    \n",
    "    fig, ax = plt.subplots(figsize=(8, 6))\n",
    "    disp.plot(cmap='YlGnBu', ax=ax, values_format='d') # Đổi màu Vàng-Xanh để sang trọng hơn\n",
    "    plt.title('Bản đồ Chiến thắng - TransMIL SOTA Confusion Matrix', fontsize=14, fontweight='bold')\n",
    "    plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

out_path = r'C:\Users\huynh\Desktop\breast cancer\05_Classification_TransMIL_SOTA.ipynb'
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)

print("Created Notebook 5 TransMIL successfully.")
