import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Notebook 6.1: Phân loại Đa phương thức (WSI + Clinical Tabular)\n",
    "**Mục tiêu:** Kết hợp đặc trưng hình thái học từ ảnh WSI và 8 chỉ số Lâm sàng & Sinh học Vĩ mô để phân loại 4 nhãn sinh học phân tử PAM50 (LumA, LumB, Basal, HER2).\n",
    "\n",
    "**Thiết kế (Late Fusion):**\n",
    "1. **Vision Stream:** Mạng TransMIL Ablation (Không PPEG) nén ảnh thành vector 512 chiều.\n",
    "2. **Clinical Stream:** Mạng MLP nén 8 chỉ số CSV thành vector 512 chiều.\n",
    "3. **Fusion:** Nối 2 nhánh lại thành 1024 chiều và đưa qua Classifier."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install nystrom-attention"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import accuracy_score, f1_score\n",
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "from nystrom_attention import NystromAttention\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1. Chuẩn bị Dữ liệu Đa phương thức (Ảnh + Bảng)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "PT_DIR = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca-resnet50-wsi-features/pt_files' \n",
    "CLINICAL_CSV = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca/tcga_brca_master_matched_cohort.csv'\n",
    "\n",
    "# Đọc Clinical CSV\n",
    "df = pd.read_csv(CLINICAL_CSV, sep='\\t')\n",
    "if len(df.columns) < 5:\n",
    "    df = pd.read_csv(CLINICAL_CSV)\n",
    "\n",
    "valid_subtypes = ['BRCA_LumA', 'BRCA_LumB', 'BRCA_Basal', 'BRCA_Her2']\n",
    "df_filtered = df[df['pam50_subtype'].isin(valid_subtypes)].copy()\n",
    "label_map = {'BRCA_LumA': 0, 'BRCA_LumB': 1, 'BRCA_Basal': 2, 'BRCA_Her2': 3}\n",
    "df_filtered['label'] = df_filtered['pam50_subtype'].map(label_map)\n",
    "\n",
    "# Chọn 8 đặc trưng vĩ mô cốt lõi\n",
    "tabular_cols = ['AGE', 'MUTATION_COUNT', 'FRACTION_GENOME_ALTERED', 'TMB_NONSYNONYMOUS', \n",
    "                'ANEUPLOIDY_SCORE', 'BUFFA_HYPOXIA_SCORE', 'RAGNUM_HYPOXIA_SCORE', 'WINTER_HYPOXIA_SCORE']\n",
    "\n",
    "# Xử lý Missing Value bằng Mean\n",
    "df_filtered[tabular_cols] = df_filtered[tabular_cols].apply(lambda col: pd.to_numeric(col, errors='coerce'))\n",
    "df_filtered[tabular_cols] = df_filtered[tabular_cols].fillna(df_filtered[tabular_cols].mean())\n",
    "\n",
    "# Chuẩn hóa dữ liệu (Z-score)\n",
    "scaler = StandardScaler()\n",
    "df_filtered[tabular_cols] = scaler.fit_transform(df_filtered[tabular_cols])\n",
    "\n",
    "patient_data = {}\n",
    "for _, row in df_filtered.iterrows():\n",
    "    patient_data[row['patientId']] = {\n",
    "        'label': int(row['label']),\n",
    "        'tabular': row[tabular_cols].values.astype(np.float32)\n",
    "    }\n",
    "\n",
    "valid_pids = [p for p in patient_data.keys() if os.path.exists(os.path.join(PT_DIR, f\"{p}.pt\"))]\n",
    "labels = [patient_data[p]['label'] for p in valid_pids]\n",
    "print(f\"Tìm thấy {len(valid_pids)} bệnh nhân có đủ Ảnh và Clinical.\")\n",
    "\n",
    "class MultimodalDataset(Dataset):\n",
    "    def __init__(self, pids, pt_dir, pat_data):\n",
    "        self.pids = pids\n",
    "        self.pt_dir = pt_dir\n",
    "        self.pat_data = pat_data\n",
    "        \n",
    "    def __len__(self):\n",
    "        return len(self.pids)\n",
    "        \n",
    "    def __getitem__(self, idx):\n",
    "        pid = self.pids[idx]\n",
    "        features = torch.load(os.path.join(self.pt_dir, f\"{pid}.pt\"), map_location='cpu')\n",
    "        tab = torch.tensor(self.pat_data[pid]['tabular'])\n",
    "        label = self.pat_data[pid]['label']\n",
    "        return features, tab, label, pid"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2. Kiến Trúc Mạng Hợp Nhất Đa Phương Thức (Late Fusion)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class TransLayer(nn.Module):\n",
    "    def __init__(self, norm_layer=nn.LayerNorm, dim=512):\n",
    "        super().__init__()\n",
    "        self.norm = norm_layer(dim)\n",
    "        self.attn = NystromAttention(dim=dim, dim_head=dim//8, heads=8, num_landmarks=dim//2, pinv_iterations=6, residual=True, dropout=0.1)\n",
    "    def forward(self, x):\n",
    "        return x + self.attn(self.norm(x))\n",
    "\n",
    "class TransMIL_Vision_Extractor(nn.Module):\n",
    "    def __init__(self, input_dim=2048, out_dim=512):\n",
    "        super().__init__()\n",
    "        self._fc1 = nn.Sequential(nn.Linear(input_dim, 512), nn.ReLU())\n",
    "        self.cls_token = nn.Parameter(torch.randn(1, 1, 512))\n",
    "        self.layer1 = TransLayer(dim=512)\n",
    "        self.layer2 = TransLayer(dim=512)\n",
    "        self.norm = nn.LayerNorm(512)\n",
    "        self.out_dim = out_dim\n",
    "        \n",
    "    def forward(self, x):\n",
    "        h = self._fc1(x.float())\n",
    "        cls_tokens = self.cls_token.expand(h.shape[0], -1, -1)\n",
    "        h = torch.cat((cls_tokens, h), dim=1)\n",
    "        h = self.layer1(h)\n",
    "        h = self.layer2(h)\n",
    "        return self.norm(h)[:,0] # Trả về vector 512\n",
    "\n",
    "class Multimodal_LateFusion(nn.Module):\n",
    "    def __init__(self, tabular_dim=8, num_classes=4):\n",
    "        super().__init__()\n",
    "        # Vision Stream (WSI)\n",
    "        self.vision_net = TransMIL_Vision_Extractor()\n",
    "        \n",
    "        # Tabular Stream (Clinical)\n",
    "        self.tabular_net = nn.Sequential(\n",
    "            nn.Linear(tabular_dim, 64),\n",
    "            nn.BatchNorm1d(64),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(64, 512),\n",
    "            nn.ReLU()\n",
    "        )\n",
    "        \n",
    "        # Fusion Classifier\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.Linear(512 + 512, 256),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(256, num_classes)\n",
    "        )\n",
    "        \n",
    "    def forward(self, img_feat, tab_feat):\n",
    "        v_img = self.vision_net(img_feat) # [1, 512]\n",
    "        v_tab = self.tabular_net(tab_feat) # [1, 512]\n",
    "        v_fusion = torch.cat((v_img, v_tab), dim=1) # [1, 1024]\n",
    "        return self.classifier(v_fusion)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3. Huấn luyện (RAdam + Accumulation)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(valid_pids) > 0:\n",
    "    class_weights = compute_class_weight('balanced', classes=np.unique(labels), y=labels)\n",
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "    class_weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)\n",
    "    criterion = nn.CrossEntropyLoss(weight=class_weights_tensor, label_smoothing=0.1)\n",
    "    \n",
    "    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
    "    epochs, batch_size, accumulation_steps = 30, 1, 16\n",
    "    fold_results = []\n",
    "\n",
    "    for fold, (train_idx, test_idx) in enumerate(skf.split(valid_pids, labels)):\n",
    "        print(f\"\\n--- [Multimodal WSI+Clinical] Fold {fold + 1}/5 ---\")\n",
    "        train_pids = [valid_pids[i] for i in train_idx]\n",
    "        test_pids = [valid_pids[i] for i in test_idx]\n",
    "        \n",
    "        train_dataset = MultimodalDataset(train_pids, PT_DIR, patient_data)\n",
    "        test_dataset = MultimodalDataset(test_pids, PT_DIR, patient_data)\n",
    "        \n",
    "        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)\n",
    "        test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)\n",
    "        \n",
    "        model = Multimodal_LateFusion().to(device)\n",
    "        optimizer = optim.RAdam(model.parameters(), lr=5e-4, weight_decay=1e-5)\n",
    "        scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-6)\n",
    "        \n",
    "        best_f1, best_acc = 0.0, 0.0\n",
    "        \n",
    "        for epoch in range(epochs):\n",
    "            model.train()\n",
    "            optimizer.zero_grad()\n",
    "            \n",
    "            for step, (img, tab, label, _) in enumerate(train_loader):\n",
    "                img, tab, label = img.to(device), tab.to(device), label.to(device)\n",
    "                logits = model(img, tab)\n",
    "                loss = criterion(logits, label) / accumulation_steps\n",
    "                loss.backward()\n",
    "                \n",
    "                if (step + 1) % accumulation_steps == 0 or (step + 1) == len(train_loader):\n",
    "                    optimizer.step()\n",
    "                    optimizer.zero_grad()\n",
    "            \n",
    "            scheduler.step()\n",
    "            model.eval()\n",
    "            preds, tgts = [], []\n",
    "            with torch.no_grad():\n",
    "                for img, tab, label, _ in test_loader:\n",
    "                    img, tab = img.to(device), tab.to(device)\n",
    "                    logits = model(img, tab)\n",
    "                    preds.extend(torch.argmax(logits, 1).cpu().numpy())\n",
    "                    tgts.extend(label.numpy())\n",
    "            \n",
    "            val_f1 = f1_score(tgts, preds, average='macro')\n",
    "            if val_f1 > best_f1:\n",
    "                best_f1, best_acc = val_f1, accuracy_score(tgts, preds)\n",
    "                \n",
    "        print(f\"Fold {fold+1} Kỷ lục: Accuracy: {best_acc:.4f} | Macro-F1: {best_f1:.4f}\")\n",
    "        fold_results.append((best_acc, best_f1))\n",
    "\n",
    "    print(\"\\n=======================================================\")\n",
    "    print(f\"TỔNG KẾT MULTIMODAL WSI + CLINICAL (5-FOLD)\")\n",
    "    print(f\"🎯 Accuracy: {np.mean([x[0] for x in fold_results]):.4f}\")\n",
    "    print(f\"⚖️ Macro-F1: {np.mean([x[1] for x in fold_results]):.4f}\")\n",
    "    print(\"=======================================================\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

out_path = r'C:\Users\huynh\Desktop\breast cancer\06.1_Multimodal_WSI_Clinical.ipynb'
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)
