import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Kế Hoạch Thực Tập: AI Y Tế Đa Phương Thức (9 Notebooks Pipeline)\n",
    "## Notebook 5.1: TransMIL Ablation Study (Khắc phục Lỗi Không Gian)\n",
    "\n",
    "**Tại sao phải có bản Ablation (Cắt bỏ) này?**\n",
    "Ở Notebook 5, phiên bản TransMIL Official gốc đã rớt đài thảm hại (F1 ~0.39). Phân tích chuyên sâu cho thấy:\n",
    "1. Lõi **PPEG** của TransMIL sử dụng mảng Conv2D để quy hoạch lại không gian tế bào.\n",
    "2. Nhưng dữ liệu `.pt` của chúng ta là các vector rời rạc, **KHÔNG CÓ** tọa độ X, Y. Các tế bào đứng cạnh nhau trong mảng chưa chắc đã nằm cạnh nhau ngoài đời thực.\n",
    "3. Việc cố tình chạy PPEG đã ép các tế bào xa lạ trở thành \"hàng xóm\", vô tình biến PPEG thành một cỗ máy tạo nhiễu (Noise Generator) hủy diệt nhận thức của Transformer.\n",
    "\n",
    "**Nhiệm vụ của Notebook 5.1:**\n",
    "- Thực hiện **Ablation Study (Nghiên cứu Cắt bỏ)**: Gỡ bỏ hoàn toàn module PPEG. Biến TransMIL thành một mô hình Vô hướng (Order-invariant).\n",
    "- Vẫn giữ lại trái tim **Nyströmformer** để xử lý hàng vạn tế bào cùng lúc.\n",
    "- Vẫn giữ lại cơ chế **[CLS] Token** để hút tín hiệu ung thư.\n",
    "- Thay vũ khí tối tân: Dùng **`torch.optim.RAdam`** (Rectified Adam) kết hợp **Gradient Accumulation** và **Label Smoothing** để ép Transformer hội tụ chính xác."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install nystrom-attention"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from tqdm import tqdm\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "import torch.nn.functional as F\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, ConfusionMatrixDisplay\n",
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "from nystrom_attention import NystromAttention\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "PT_DIR = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca-resnet50-wsi-features/pt_files' \n",
    "CLINICAL_CSV = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca/tcga_brca_master_matched_cohort.csv'\n",
    "\n",
    "df = pd.read_csv(CLINICAL_CSV, sep='\\t')\n",
    "if len(df.columns) < 5:\n",
    "    df = pd.read_csv(CLINICAL_CSV)\n",
    "\n",
    "valid_subtypes = ['BRCA_LumA', 'BRCA_LumB', 'BRCA_Basal', 'BRCA_Her2']\n",
    "df_filtered = df[df['pam50_subtype'].isin(valid_subtypes)].copy()\n",
    "label_map = {'BRCA_LumA': 0, 'BRCA_LumB': 1, 'BRCA_Basal': 2, 'BRCA_Her2': 3}\n",
    "df_filtered['label'] = df_filtered['pam50_subtype'].map(label_map)\n",
    "patient_label_dict = dict(zip(df_filtered['patientId'], df_filtered['label']))\n",
    "\n",
    "class MILBagDataset(Dataset):\n",
    "    def __init__(self, patient_ids, pt_dir, label_dict):\n",
    "        self.patient_ids = patient_ids\n",
    "        self.pt_dir = pt_dir\n",
    "        self.label_dict = label_dict\n",
    "        \n",
    "    def __len__(self):\n",
    "        return len(self.patient_ids)\n",
    "        \n",
    "    def __getitem__(self, idx):\n",
    "        pid = self.patient_ids[idx]\n",
    "        pt_path = os.path.join(self.pt_dir, f\"{pid}.pt\")\n",
    "        features = torch.load(pt_path, map_location='cpu') # Shape: [N, 2048]\n",
    "        label = self.label_dict[pid]\n",
    "        return features, label, pid\n",
    "\n",
    "if os.path.exists(PT_DIR):\n",
    "    valid_pids = [p for p in df_filtered['patientId'].tolist() if os.path.exists(os.path.join(PT_DIR, f\"{p}.pt\"))]\n",
    "    labels = [patient_label_dict[pid] for pid in valid_pids]\n",
    "    print(f\"Tìm thấy {len(valid_pids)} bệnh nhân hợp lệ.\")\n",
    "else:\n",
    "    print(\"Lỗi: Không tìm thấy thư mục PT_DIR.\")\n",
    "    valid_pids, labels = [], []"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2. Mô Hình TransMIL (Bản Cắt Bỏ PPEG - Vô Hướng)\n",
    "Lưu ý: Bạn sẽ thấy module PPEG bị gạch bỏ hoàn toàn khỏi luồng `forward`. Không còn việc ép chuỗi thành lưới vuông `_H x _W` nữa!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class TransLayer(nn.Module):\n",
    "    def __init__(self, norm_layer=nn.LayerNorm, dim=512):\n",
    "        super().__init__()\n",
    "        self.norm = norm_layer(dim)\n",
    "        self.attn = NystromAttention(\n",
    "            dim = dim,\n",
    "            dim_head = dim//8,\n",
    "            heads = 8,\n",
    "            num_landmarks = dim//2,    \n",
    "            pinv_iterations = 6,    \n",
    "            residual = True,         \n",
    "            dropout=0.1\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = x + self.attn(self.norm(x))\n",
    "        return x\n",
    "\n",
    "class TransMIL_Ablation(nn.Module):\n",
    "    def __init__(self, input_dim=2048, n_classes=4):\n",
    "        super(TransMIL_Ablation, self).__init__()\n",
    "        \n",
    "        # Nén từ 2048 xuống 512\n",
    "        self._fc1 = nn.Sequential(nn.Linear(input_dim, 512), nn.ReLU())\n",
    "        \n",
    "        # Gián điệp CLS Token hút thông tin ung thư\n",
    "        self.cls_token = nn.Parameter(torch.randn(1, 1, 512))\n",
    "        self.n_classes = n_classes\n",
    "        \n",
    "        # 2 Lớp Nyströmformer tốc độ cao\n",
    "        self.layer1 = TransLayer(dim=512)\n",
    "        self.layer2 = TransLayer(dim=512)\n",
    "        \n",
    "        self.norm = nn.LayerNorm(512)\n",
    "        self._fc2 = nn.Linear(512, self.n_classes)\n",
    "\n",
    "    def forward(self, x):\n",
    "        # x: [1, N, 2048]\n",
    "        h = x.float()\n",
    "        h = self._fc1(h) # [1, N, 512]\n",
    "        \n",
    "        # ----> [ĐÃ CẮT BỎ] KHÔNG ép thành hình vuông _H x _W\n",
    "        # ----> [ĐÃ CẮT BỎ] KHÔNG dùng PPEG Convolution gây nhiễu\n",
    "\n",
    "        # ----> Thêm [CLS] Token\n",
    "        B = h.shape[0]\n",
    "        cls_tokens = self.cls_token.expand(B, -1, -1)\n",
    "        h = torch.cat((cls_tokens, h), dim=1) # [1, N + 1, 512]\n",
    "\n",
    "        # ----> Nyström Attention Layer 1\n",
    "        h = self.layer1(h) \n",
    "        \n",
    "        # ----> Nyström Attention Layer 2\n",
    "        h = self.layer2(h) \n",
    "\n",
    "        # ----> Gom kết quả từ [CLS] Token\n",
    "        h = self.norm(h)[:,0]\n",
    "\n",
    "        # ----> Phân loại\n",
    "        logits = self._fc2(h) # [1, 4]\n",
    "        return logits, None"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3. Vòng Lặp Huấn Luyện Trang Bị \"Tận Răng\" (RAdam + Accumulation)\n",
    "Để trị căn bệnh \"say sóng\" của Transformer, ta dùng 3 liều thuốc mạnh:\n",
    "1. **RAdam (Rectified Adam):** Kìm hãm sự hưng phấn quá đà ở những epoch đầu tiên.\n",
    "2. **Gradient Accumulation = 16:** Đọc 16 bệnh nhân mới cập nhật trọng số 1 lần.\n",
    "3. **Label Smoothing = 0.1:** Cấm mô hình không được tin tưởng 100% vào nhãn đa số."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(valid_pids) > 0:\n",
    "    class_weights = compute_class_weight('balanced', classes=np.unique(labels), y=labels)\n",
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "    class_weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)\n",
    "    \n",
    "    # Thuốc 1: Label Smoothing\n",
    "    criterion = nn.CrossEntropyLoss(weight=class_weights_tensor, label_smoothing=0.1)\n",
    "    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
    "    \n",
    "    epochs = 30 # Kéo dài thời gian train vì RAdam học khá chậm và chắc\n",
    "    batch_size = 1 \n",
    "    # Thuốc 2: Gradient Accumulation\n",
    "    accumulation_steps = 16 \n",
    "    \n",
    "    fold_results = []\n",
    "    best_global_preds = []\n",
    "    best_global_labels = []\n",
    "\n",
    "    print(f\"Khởi động lò nung TransMIL Ablation trên thiết bị: {device}\")\n",
    "    \n",
    "    for fold, (train_idx, test_idx) in enumerate(skf.split(valid_pids, labels)):\n",
    "        print(f\"\\n--- Bắt đầu Fold {fold + 1}/5 ---\")\n",
    "        \n",
    "        train_pids = [valid_pids[i] for i in train_idx]\n",
    "        test_pids = [valid_pids[i] for i in test_idx]\n",
    "        \n",
    "        train_dataset = MILBagDataset(train_pids, PT_DIR, patient_label_dict)\n",
    "        test_dataset = MILBagDataset(test_pids, PT_DIR, patient_label_dict)\n",
    "        \n",
    "        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)\n",
    "        test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)\n",
    "        \n",
    "        model = TransMIL_Ablation(input_dim=2048, n_classes=4).to(device)\n",
    "        \n",
    "        # Thuốc 3: RAdam siêu hội tụ\n",
    "        optimizer = optim.RAdam(model.parameters(), lr=5e-4, weight_decay=1e-5)\n",
    "        scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-6)\n",
    "        \n",
    "        best_f1 = 0.0\n",
    "        best_acc = 0.0\n",
    "        fold_preds = []\n",
    "        fold_labels = []\n",
    "        \n",
    "        for epoch in range(epochs):\n",
    "            model.train()\n",
    "            optimizer.zero_grad()\n",
    "            \n",
    "            for step, (features, label, _) in enumerate(train_loader):\n",
    "                features, label = features.to(device), label.to(device)\n",
    "                \n",
    "                logits, _ = model(features)\n",
    "                loss = criterion(logits, label)\n",
    "                loss = loss / accumulation_steps \n",
    "                loss.backward()\n",
    "                \n",
    "                if (step + 1) % accumulation_steps == 0 or (step + 1) == len(train_loader):\n",
    "                    optimizer.step()\n",
    "                    optimizer.zero_grad()\n",
    "            \n",
    "            scheduler.step()\n",
    "            \n",
    "            model.eval()\n",
    "            epoch_preds = []\n",
    "            epoch_labels = []\n",
    "            with torch.no_grad():\n",
    "                for features, label, _ in test_loader:\n",
    "                    features, label = features.to(device), label.to(device)\n",
    "                    logits, _ = model(features)\n",
    "                    _, pred = torch.max(logits, 1)\n",
    "                    epoch_preds.extend(pred.cpu().numpy())\n",
    "                    epoch_labels.extend(label.cpu().numpy())\n",
    "            \n",
    "            val_acc = accuracy_score(epoch_labels, epoch_preds)\n",
    "            val_f1 = f1_score(epoch_labels, epoch_preds, average='macro')\n",
    "            \n",
    "            if val_f1 > best_f1:\n",
    "                best_f1 = val_f1\n",
    "                best_acc = val_acc\n",
    "                fold_preds = epoch_preds\n",
    "                fold_labels = epoch_labels\n",
    "                \n",
    "        print(f\"Fold {fold+1} Kỷ lục mới - Accuracy: {best_acc:.4f} | Macro-F1: {best_f1:.4f}\")\n",
    "        fold_results.append((best_acc, best_f1))\n",
    "        best_global_preds.extend(fold_preds)\n",
    "        best_global_labels.extend(fold_labels)\n",
    "    \n",
    "    mean_acc = np.mean([x[0] for x in fold_results])\n",
    "    std_acc = np.std([x[0] for x in fold_results])\n",
    "    mean_f1 = np.mean([x[1] for x in fold_results])\n",
    "    std_f1 = np.std([x[1] for x in fold_results])\n",
    "    \n",
    "    print(\"\\n=======================================================\")\n",
    "    print(\" TỔNG KẾT TRANSMIL ABLATION STUDY (5-FOLD)\")\n",
    "    print(\"=======================================================\")\n",
    "    print(f\"🎯 Khôi phục phong độ: Accuracy: {mean_acc:.4f} ˙ {std_acc:.4f}\")\n",
    "    print(f\"⚖️ Giới hạn F1: Macro-F1: {mean_f1:.4f} ˙ {std_f1:.4f}\")\n",
    "    print(\"=======================================================\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(valid_pids) > 0:\n",
    "    cm = confusion_matrix(best_global_labels, best_global_preds)\n",
    "    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['LumA', 'LumB', 'Basal', 'HER2'])\n",
    "    \n",
    "    fig, ax = plt.subplots(figsize=(8, 6))\n",
    "    disp.plot(cmap='OrRd', ax=ax, values_format='d') # Màu đỏ lửa tượng trưng cho Ablation\n",
    "    plt.title('Bản đồ TransMIL Ablation Confusion Matrix', fontsize=14, fontweight='bold')\n",
    "    plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

out_path = r'C:\Users\huynh\Desktop\breast cancer\05.1_Classification_TransMIL_Ablation.ipynb'
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)

print("Created Notebook 5.1 Ablation successfully.")
