import json

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Notebook 6.6: Huấn luyện Đa phương thức (WSI BiLSTM + Genomics RNA-Seq)\n",
    "**Mục tiêu:** Áp dụng mạng **BiLSTM (Bidirectional LSTM)** để xử lý đặc trưng ảnh WSI, thay thế cho kiến trúc Transformer (TransMIL). \n",
    "\n",
    "Đây là notebook **thực hành hoàn chỉnh** nhằm đáp ứng yêu cầu bắt buộc của Giảng viên (Phải triển khai thuật toán LSTM trên dữ liệu Y tế). Notebook này không chỉ thiết kế kiến trúc mà còn thực hiện Huấn luyện (Train), Đánh giá 5-Fold Cross Validation và tính toán đủ **5 chỉ số cực kỳ quan trọng**: `Accuracy`, `Precision`, `Recall`, `F1-Score` và `AUC`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, confusion_matrix, ConfusionMatrixDisplay\n",
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "import torch.nn.functional as F\n",
    "import matplotlib.pyplot as plt\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "plt.rcParams['font.family'] = 'sans-serif'\n",
    "plt.rcParams['font.sans-serif'] = ['Arial', 'Tahoma', 'DejaVu Sans']\n",
    "plt.rcParams['axes.unicode_minus'] = False"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Nạp Dữ liệu và pad_collate\n",
    "Tương tự như Notebook 6.2, ta sẽ nạp 500 gen đã xử lý Variance Threshold từ trước."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "PT_DIR = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca-resnet50-wsi-features/pt_files' \n",
    "RNASEQ_FILE = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca/data_mrna_seq_v2_rsem.txt'\n",
    "CLINICAL_CSV = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca/tcga_brca_master_matched_cohort.csv'\n",
    "\n",
    "print(\"Đang tải dữ liệu Gen & Tiền xử lý...\")\n",
    "rna_df = pd.read_csv(RNASEQ_FILE, sep='\\t')\n",
    "if 'Entrez_Gene_Id' in rna_df.columns:\n",
    "    rna_df = rna_df.drop(columns=['Entrez_Gene_Id'])\n",
    "rna_df = rna_df.set_index('Hugo_Symbol').T\n",
    "rna_df.index = rna_df.index.str[:12]\n",
    "rna_df = rna_df[~rna_df.index.duplicated(keep='first')]\n",
    "rna_df = rna_df.dropna(axis=1)\n",
    "\n",
    "variances = rna_df.var()\n",
    "top_500_genes = variances.nlargest(500).index\n",
    "rna_500 = rna_df[top_500_genes]\n",
    "\n",
    "scaler = StandardScaler()\n",
    "rna_500_scaled = pd.DataFrame(scaler.fit_transform(rna_500), index=rna_500.index)\n",
    "\n",
    "df_clin = pd.read_csv(CLINICAL_CSV, sep='\\t')\n",
    "if len(df_clin.columns) < 5:\n",
    "    df_clin = pd.read_csv(CLINICAL_CSV)\n",
    "valid_subtypes = ['BRCA_LumA', 'BRCA_LumB', 'BRCA_Basal', 'BRCA_Her2']\n",
    "df_clin = df_clin[df_clin['pam50_subtype'].isin(valid_subtypes)].copy()\n",
    "label_map = {'BRCA_LumA': 0, 'BRCA_LumB': 1, 'BRCA_Basal': 2, 'BRCA_Her2': 3}\n",
    "df_clin['label'] = df_clin['pam50_subtype'].map(label_map)\n",
    "label_dict = dict(zip(df_clin['patientId'], df_clin['label']))\n",
    "\n",
    "valid_pids = []\n",
    "for pid in label_dict.keys():\n",
    "    if pid in rna_500_scaled.index and os.path.exists(os.path.join(PT_DIR, f\"{pid}.pt\")):\n",
    "        valid_pids.append(pid)\n",
    "labels = [label_dict[pid] for pid in valid_pids]\n",
    "print(f\"✓ Tập Đa phương thức hợp lệ: {len(valid_pids)} bệnh nhân.\")\n",
    "\n",
    "class GenomicsDataset(Dataset):\n",
    "    def __init__(self, pids, pt_dir, rna_data, label_map):\n",
    "        self.pids = pids\n",
    "        self.pt_dir = pt_dir\n",
    "        self.rna_data = rna_data\n",
    "        self.label_map = label_map\n",
    "    def __len__(self): return len(self.pids)\n",
    "    def __getitem__(self, idx):\n",
    "        pid = self.pids[idx]\n",
    "        img = torch.load(os.path.join(self.pt_dir, f\"{pid}.pt\"), map_location='cpu')\n",
    "        genomics = torch.tensor(self.rna_data.loc[pid].values, dtype=torch.float32)\n",
    "        return img, genomics, self.label_map[pid], pid\n",
    "\n",
    "def pad_collate(batch):\n",
    "    imgs = [item[0] for item in batch]\n",
    "    tabs = [item[1] for item in batch]\n",
    "    labels = [item[2] for item in batch]\n",
    "    pids = [item[3] for item in batch]\n",
    "    \n",
    "    max_len = max([img.size(0) for img in imgs])\n",
    "    padded_imgs = []\n",
    "    for img in imgs:\n",
    "        pad_size = max_len - img.size(0)\n",
    "        if pad_size > 0:\n",
    "            padded = F.pad(img, (0, 0, 0, pad_size), \"constant\", 0)\n",
    "        else:\n",
    "            padded = img\n",
    "        padded_imgs.append(padded)\n",
    "        \n",
    "    return torch.stack(padded_imgs, dim=0), torch.stack(tabs, dim=0), torch.tensor(labels), pids"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Kiến trúc BiLSTM-MIL + Genomics\n",
    "BiLSTM quét qua hàng ngàn bản vá hình ảnh từ trái qua phải và ngược lại, trích xuất đặc trưng không gian. Đặc trưng này (512 chiều) sau đó ghép nối với dữ liệu gen (512 chiều) để phân loại."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class BiLSTM_Vision_Extractor(nn.Module):\n",
    "    def __init__(self, input_dim=2048, out_dim=512):\n",
    "        super().__init__()\n",
    "        self.fc1 = nn.Sequential(nn.Linear(input_dim, 512), nn.ReLU())\n",
    "        # LSTM 2 chiều (Bidirectional = True)\n",
    "        self.lstm = nn.LSTM(input_size=512, hidden_size=256, num_layers=2, \n",
    "                            batch_first=True, bidirectional=True, dropout=0.2)\n",
    "        \n",
    "    def forward(self, x):\n",
    "        h = self.fc1(x.float())  # [B, L, 512]\n",
    "        lstm_out, _ = self.lstm(h) # [B, L, 512]\n",
    "        # Global Average Pooling trên toàn bộ Sequence (Chuỗi patch)\n",
    "        return lstm_out.mean(dim=1)\n",
    "\n",
    "class Multimodal_LSTM_Genomics(nn.Module):\n",
    "    def __init__(self, genomics_dim=500, num_classes=4):\n",
    "        super().__init__()\n",
    "        self.vision_net = BiLSTM_Vision_Extractor()\n",
    "        self.genomics_net = nn.Sequential(\n",
    "            nn.Linear(genomics_dim, 256),\n",
    "            nn.LayerNorm(256),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(256, 512),\n",
    "            nn.ReLU()\n",
    "        )\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.Linear(512 + 512, 256),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(256, num_classes)\n",
    "        )\n",
    "        \n",
    "    def forward(self, img_feat, gen_feat):\n",
    "        v_img = self.vision_net(img_feat)\n",
    "        v_gen = self.genomics_net(gen_feat)\n",
    "        v_fusion = torch.cat((v_img, v_gen), dim=1)\n",
    "        return self.classifier(v_fusion)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Huấn luyện và Trích xuất 5 Chỉ số (Acc, Prec, Rec, F1, AUC)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(valid_pids) > 0:\n",
    "    class_weights = compute_class_weight('balanced', classes=np.unique(labels), y=labels)\n",
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "    class_weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)\n",
    "    criterion = nn.CrossEntropyLoss(weight=class_weights_tensor, label_smoothing=0.1)\n",
    "    \n",
    "    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
    "    epochs, batch_size, accumulation_steps = 30, 2, 8\n",
    "    \n",
    "    metrics_list = []\n",
    "    best_global_preds = []\n",
    "    best_global_labels = []\n",
    "\n",
    "    for fold, (train_idx, test_idx) in enumerate(skf.split(valid_pids, labels)):\n",
    "        print(f\"\\n--- [BiLSTM + Genomics] Fold {fold + 1}/5 ---\")\n",
    "        train_loader = DataLoader(GenomicsDataset([valid_pids[i] for i in train_idx], PT_DIR, rna_500_scaled, label_dict), \n",
    "                                  batch_size=batch_size, shuffle=True, collate_fn=pad_collate)\n",
    "        test_loader = DataLoader(GenomicsDataset([valid_pids[i] for i in test_idx], PT_DIR, rna_500_scaled, label_dict), \n",
    "                                 batch_size=batch_size, shuffle=False, collate_fn=pad_collate)\n",
    "        \n",
    "        model = Multimodal_LSTM_Genomics().to(device)\n",
    "        if torch.cuda.device_count() > 1:\n",
    "            model = nn.DataParallel(model)\n",
    "            \n",
    "        optimizer = optim.RAdam(model.parameters(), lr=5e-4, weight_decay=1e-5)\n",
    "        scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-6)\n",
    "        \n",
    "        best_f1 = 0.0\n",
    "        best_metrics = {}\n",
    "        fold_preds, fold_labels = [], []\n",
    "        \n",
    "        for epoch in range(epochs):\n",
    "            model.train()\n",
    "            optimizer.zero_grad()\n",
    "            for step, (img, gen, label, _) in enumerate(train_loader):\n",
    "                logits = model(img.to(device), gen.to(device))\n",
    "                loss = criterion(logits, label.to(device)) / accumulation_steps\n",
    "                loss.backward()\n",
    "                if (step + 1) % accumulation_steps == 0 or (step + 1) == len(train_loader):\n",
    "                    optimizer.step()\n",
    "                    optimizer.zero_grad()\n",
    "            scheduler.step()\n",
    "            \n",
    "            model.eval()\n",
    "            preds, tgts, probs_all = [], [], []\n",
    "            with torch.no_grad():\n",
    "                for img, gen, label, _ in test_loader:\n",
    "                    logits = model(img.to(device), gen.to(device))\n",
    "                    probs = torch.softmax(logits, dim=1)\n",
    "                    preds.extend(torch.argmax(logits, 1).cpu().numpy())\n",
    "                    tgts.extend(label.numpy())\n",
    "                    probs_all.extend(probs.cpu().numpy())\n",
    "            \n",
    "            val_f1 = f1_score(tgts, preds, average='macro')\n",
    "            if val_f1 > best_f1:\n",
    "                best_f1 = val_f1\n",
    "                best_metrics = {\n",
    "                    'acc': accuracy_score(tgts, preds),\n",
    "                    'prec': precision_score(tgts, preds, average='macro'),\n",
    "                    'rec': recall_score(tgts, preds, average='macro'),\n",
    "                    'f1': val_f1,\n",
    "                    'auc': roc_auc_score(tgts, probs_all, multi_class='ovr')\n",
    "                }\n",
    "                fold_preds, fold_labels = preds, tgts\n",
    "                torch.save(model.state_dict(), f'/kaggle/working/multimodal_lstm_fold{fold+1}.pth')\n",
    "                \n",
    "        print(f\"Fold {fold+1} | Acc: {best_metrics['acc']:.4f} | Prec: {best_metrics['prec']:.4f} | Rec: {best_metrics['rec']:.4f} | F1: {best_metrics['f1']:.4f} | AUC: {best_metrics['auc']:.4f}\")\n",
    "        metrics_list.append(best_metrics)\n",
    "        best_global_preds.extend(fold_preds)\n",
    "        best_global_labels.extend(fold_labels)\n",
    "\n",
    "    print(\"\\n=======================================================\")\n",
    "    print(f\"TỔNG KẾT MÔ HÌNH MULTIMODAL LSTM (5-FOLD CROSS VALIDATION)\")\n",
    "    print(f\"🔹 Accuracy  : {np.mean([m['acc'] for m in metrics_list]):.4f}\")\n",
    "    print(f\"🔹 Precision : {np.mean([m['prec'] for m in metrics_list]):.4f}\")\n",
    "    print(f\"🔹 Recall    : {np.mean([m['rec'] for m in metrics_list]):.4f}\")\n",
    "    print(f\"🔹 F1-Score  : {np.mean([m['f1'] for m in metrics_list]):.4f}\")\n",
    "    print(f\"🔹 AUC (OVR) : {np.mean([m['auc'] for m in metrics_list]):.4f}\")\n",
    "    print(\"=======================================================\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(valid_pids) > 0:\n",
    "    cm = confusion_matrix(best_global_labels, best_global_preds)\n",
    "    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['LumA', 'LumB', 'Basal', 'HER2'])\n",
    "    fig, ax = plt.subplots(figsize=(8, 6))\n",
    "    disp.plot(cmap='Purples', ax=ax, values_format='d')\n",
    "    plt.title('Confusion Matrix - Multimodal BiLSTM', fontsize=14, fontweight='bold')\n",
    "    plt.show()"
   ]
  }
 ]
}

with open(r'C:\Users\huynh\Desktop\breast cancer\06.6_Multimodal_WSI_BiLSTM_Genomics_Train.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook_content, f, indent=1, ensure_ascii=False)

print("Đã tạo file Notebook LSTM huấn luyện đầy đủ.")
