import json

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Notebook 6.6: Thuc hanh Huan luyen BiLSTM - Mang Bo Nho Ngan Han Dao Chieu (WSI + Genomics)\n",
    "---\n",
    "## Muc dich cua Notebook (Dung de Trinh chieu & Bao ve)\n",
    "Notebook nay duoc thiet ke de giai quyet dut diem yeu cau cua Hoi dong: **\"Phai co ung dung mang LSTM trong xu ly du lieu\"**.\n",
    "\n",
    "Tuy nhien, chung ta khong dung LSTM mot cach khien cuong. Chung ta su dung **BiLSTM (Bidirectional LSTM)** de xu ly hinh anh WSI theo mot triet ly Y Sinh cuc ky chat che:\n",
    "- Mot tam lam kinh (WSI) cua benh nhan qua to, chua hang ty pixel. Ta phai cat no thanh hang ngan ban va (patches).\n",
    "- Hang ngan ban va nay duoc sap xep thanh mot **\"Chuoi khong gian\" (Spatial Sequence)**.\n",
    "- Mang **Bi-LSTM** se truot qua chuoi anh nay tu trai sang phai, roi lai tu phai sang trai (2 chieu). No dong vai tro nhu mot **\"May Quet Benh Ly\"**, ghi nho (Memory) cac te bao ac tinh xuat hien doc theo mat kinh, sau do tong hop lai thanh 1 ket luan duy nhat cho toan bo khoi u.\n",
    "\n",
    "Notebook nay duoc chia nho tung phan (Layer-by-Layer), giai thich **TUNG THAM SO CODE** de ban dung lam \"phao cuu sinh\" khi bi Giang vien Phan bien hoi xoay."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Khai bao cac thu vien thiet yeu\n",
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import torch.nn.functional as F\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.preprocessing import StandardScaler, label_binarize\n",
    "from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, confusion_matrix, ConfusionMatrixDisplay, roc_curve, auc\n",
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "import matplotlib.pyplot as plt\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "# ---------------------------------------------------------\n",
    "# CAU HINH FONT TIENG VIET QUOC DAN CHO MATPLOTLIB\n",
    "# (Chong loi font hien thi hinh o vuong tren Kaggle/Windows)\n",
    "# ---------------------------------------------------------\n",
    "plt.rcParams['font.family'] = 'sans-serif'\n",
    "plt.rcParams['font.sans-serif'] = ['Arial', 'Tahoma', 'DejaVu Sans']\n",
    "plt.rcParams['axes.unicode_minus'] = False\n",
    "print(\"Khoi tao moi truong hoan tat!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Nap Du Lieu (Genomics & Clinical)\n",
    "O buoc nay, ta nap du lieu Gen RNA-Seq. Bang goc co 20,500 gen, neu dua thang vao AI se gay ra **\"Loi nguyen so chieu\" (Curse of Dimensionality)**, khien mo hinh hoc vet (Overfit).\n",
    "\n",
    "**Cach giai quyet:** Ap dung thuat toan **Variance Threshold** de chon ra dung 500 gen co phuong sai (su bien dong) cao nhat giua cac benh nhan. Day chinh la cac Gen sinh ung thu (Biomarkers) quan trong nhat."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "PT_DIR = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca-resnet50-wsi-features/pt_files' \n",
    "RNASEQ_FILE = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca/data_mrna_seq_v2_rsem.txt'\n",
    "CLINICAL_CSV = '/kaggle/input/datasets/trihuynhviprovcl/tcga-brca/tcga_brca_master_matched_cohort.csv'\n",
    "\n",
    "print(\"Dang nap ma tran RNA-Seq...\")\n",
    "rna_df = pd.read_csv(RNASEQ_FILE, sep='\\t')\n",
    "if 'Entrez_Gene_Id' in rna_df.columns:\n",
    "    rna_df = rna_df.drop(columns=['Entrez_Gene_Id'])\n",
    "\n",
    "# Dao ma tran (Chuyen vi): Benh nhan nam o Hang, 20500 Gen nam o Cot\n",
    "rna_df = rna_df.set_index('Hugo_Symbol').T\n",
    "rna_df.index = rna_df.index.str[:12] # Lay ma TCGA-XX-XXXX (12 ky tu)\n",
    "rna_df = rna_df[~rna_df.index.duplicated(keep='first')] # Xoa benh nhan trung\n",
    "rna_df = rna_df.dropna(axis=1)\n",
    "\n",
    "# TINH PHUONG SAI & LOC TOP 500 GEN\n",
    "variances = rna_df.var()\n",
    "top_500_genes = variances.nlargest(500).index\n",
    "rna_500 = rna_df[top_500_genes]\n",
    "\n",
    "# CHUAN HOA Z-SCORE: Keo moi gen ve Mean=0, Std=1 de mang Neural de hoi tu\n",
    "scaler = StandardScaler()\n",
    "rna_500_scaled = pd.DataFrame(scaler.fit_transform(rna_500), index=rna_500.index)\n",
    "\n",
    "# LOC NHAN TU LAM SANG (Lay 4 phan nhom PAM50)\n",
    "df_clin = pd.read_csv(CLINICAL_CSV, sep='\\t')\n",
    "if len(df_clin.columns) < 5:\n",
    "    df_clin = pd.read_csv(CLINICAL_CSV)\n",
    "valid_subtypes = ['BRCA_LumA', 'BRCA_LumB', 'BRCA_Basal', 'BRCA_Her2']\n",
    "df_clin = df_clin[df_clin['pam50_subtype'].isin(valid_subtypes)].copy()\n",
    "label_map = {'BRCA_LumA': 0, 'BRCA_LumB': 1, 'BRCA_Basal': 2, 'BRCA_Her2': 3}\n",
    "df_clin['label'] = df_clin['pam50_subtype'].map(label_map)\n",
    "label_dict = dict(zip(df_clin['patientId'], df_clin['label']))\n",
    "\n",
    "# TIM GIAO DIEM (COHORT MATCHING) GIUA WSI & GEN & LAM SANG\n",
    "valid_pids = []\n",
    "for pid in label_dict.keys():\n",
    "    if pid in rna_500_scaled.index and os.path.exists(os.path.join(PT_DIR, f\"{pid}.pt\")):\n",
    "        valid_pids.append(pid)\n",
    "labels = [label_dict[pid] for pid in valid_pids]\n",
    "print(f\"Xong! Tim thay {len(valid_pids)} benh nhan co DU 3 loai du lieu (Anh + Gen + Nhan Lam sang).\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Ky thuat Zero-Padding & Dataset\n",
    "**Hoi:** *Tai sao lai co ham `pad_collate` phuc tap the nay?*\n",
    "**Dap:** Vi khoi u cua benh nhan to nho khac nhau. Nguoi cat duoc 1000 anh con (patch), nguoi chi cat duoc 50 anh. GPU khong the nhan 1 Batch du lieu bi lech kich thuoc. Ham `pad_collate` se tim benh nhan co nhieu anh nhat trong Batch, sau do **nhet them so 0 (Zero-padding)** vao duoi cac benh nhan khac de tat ca bang nhau."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class GenomicsDataset(Dataset):\n",
    "    def __init__(self, pids, pt_dir, rna_data, label_map):\n",
    "        self.pids = pids\n",
    "        self.pt_dir = pt_dir\n",
    "        self.rna_data = rna_data\n",
    "        self.label_map = label_map\n",
    "    def __len__(self): return len(self.pids)\n",
    "    \n",
    "    def __getitem__(self, idx):\n",
    "        pid = self.pids[idx]\n",
    "        # Load tensor anh (.pt) luu boi ResNet50\n",
    "        img = torch.load(os.path.join(self.pt_dir, f\"{pid}.pt\"), map_location='cpu')\n",
    "        # Load dong 500 gen cua benh nhan do\n",
    "        genomics = torch.tensor(self.rna_data.loc[pid].values, dtype=torch.float32)\n",
    "        return img, genomics, self.label_map[pid], pid\n",
    "\n",
    "def pad_collate(batch):\n",
    "    imgs = [item[0] for item in batch]\n",
    "    tabs = [item[1] for item in batch]\n",
    "    labels = [item[2] for item in batch]\n",
    "    pids = [item[3] for item in batch]\n",
    "    \n",
    "    # Tim chieu dai dai nhat\n",
    "    max_len = max([img.size(0) for img in imgs])\n",
    "    padded_imgs = []\n",
    "    for img in imgs:\n",
    "        pad_size = max_len - img.size(0)\n",
    "        if pad_size > 0:\n",
    "            # Ham dem (pad) bang so 0\n",
    "            padded = F.pad(img, (0, 0, 0, pad_size), \"constant\", 0)\n",
    "        else:\n",
    "            padded = img\n",
    "        padded_imgs.append(padded)\n",
    "        \n",
    "    return torch.stack(padded_imgs, dim=0), torch.stack(tabs, dim=0), torch.tensor(labels), pids"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Khai bao Kien Truc BiLSTM cho Hinh anh (Vision Encoder)\n",
    "Day la linh hon cua mang luoi, thay the cho TransMIL. Can luu y cac tham so sau:\n",
    "- `input_dim=2048`: Do mang ResNet50 ban dau tao ra chuoi dac trung 2048 chieu.\n",
    "- Tang `fc1`: Bop 2048 xuong 512 de giam chi phi tinh toan, tranh bung no RAM GPU.\n",
    "- `nn.LSTM(..., bidirectional=True)`: Mang Bo nho Ngan han Dao chieu. No luot qua chuoi anh 2 lan (Tu trai sang phai va nguoc lai). \n",
    "- Tai sao `hidden_size=256`? Vi mang chay 2 chieu, nen dau ra se tu dong chap lai thanh `256 * 2 = 512` chieu.\n",
    "- `mean(dim=1)`: Ky thuat Global Average Pooling. Tinh trung binh cong cua toan bo hang ngan ban va de gom thanh 1 vector duy nhat 512 chieu dai dien cho cuc u."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class BiLSTM_Vision_Extractor(nn.Module):\n",
    "    def __init__(self, input_dim=2048, out_dim=512):\n",
    "        super().__init__()\n",
    "        self.fc1 = nn.Sequential(nn.Linear(input_dim, 512), nn.ReLU())\n",
    "        \n",
    "        # KHAI BAO BI-LSTM TOI THUONG\n",
    "        self.lstm = nn.LSTM(\n",
    "            input_size=512, \n",
    "            hidden_size=256, \n",
    "            num_layers=2,           # 2 tang LSTM chong len nhau de hoc sau hon\n",
    "            batch_first=True,       # Bat buoc True vi batch tensor cua ta dang o dau: [Batch, Seq, Dim]\n",
    "            bidirectional=True,     # Quet 2 chieu\n",
    "            dropout=0.2             # Ban bo ngau nhien 20% no-ron de chong Overfitting\n",
    "        )\n",
    "        \n",
    "    def forward(self, x):\n",
    "        # x co shape: [Batch_size, So_anh_patch, 2048]\n",
    "        h = self.fc1(x.float())  # Xuong con [Batch, So_anh, 512]\n",
    "        \n",
    "        lstm_out, _ = self.lstm(h) # lstm_out co shape: [Batch, So_anh, 512]\n",
    "        \n",
    "        # Gop tat ca cac anh lai bang Trung binh (Global Average Pooling)\n",
    "        final_wsi = lstm_out.mean(dim=1) # Tro thanh [Batch, 512]\n",
    "        return final_wsi"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Hop nhat Da phuong thuc (Late Fusion)\n",
    "Nhanh Gen chi co 500 so, rat don gian nen ta dung mot mang chap (MLP) gom cac tang Linear. Cuoi cung, hai vector 512 (Anh) va 512 (Gen) duoc noi voi nhau qua lenh than thanh `torch.cat` tao thanh vector 1024, roi nem vao lop Classifier (4 class)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class Multimodal_LSTM_Genomics(nn.Module):\n",
    "    def __init__(self, genomics_dim=500, num_classes=4):\n",
    "        super().__init__()\n",
    "        self.vision_net = BiLSTM_Vision_Extractor()\n",
    "        \n",
    "        # NHANH GENOMICS MLP\n",
    "        self.genomics_net = nn.Sequential(\n",
    "            nn.Linear(genomics_dim, 256),\n",
    "            nn.LayerNorm(256),  # Dung LayerNorm thay BatchNorm de tranh Crash khi Batch size qua nho\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(256, 512),\n",
    "            nn.ReLU()\n",
    "        )\n",
    "        \n",
    "        # TANG PHAN LOAI CUOI CUNG (CLASSIFIER)\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.Linear(512 + 512, 256), # 512 Vision + 512 Gen = 1024 Fusion\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(256, num_classes) # Dau ra 4 nhan ung thu\n",
    "        )\n",
    "        \n",
    "    def forward(self, img_feat, gen_feat):\n",
    "        v_img = self.vision_net(img_feat)\n",
    "        v_gen = self.genomics_net(gen_feat)\n",
    "        \n",
    "        # LATE FUSION (Gan canh WSI vao canh Gen)\n",
    "        v_fusion = torch.cat((v_img, v_gen), dim=1)\n",
    "        return self.classifier(v_fusion)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Chuan bi Tham so Huan luyen & 5 Chi so Danh gia (Metrics)\n",
    "Phan nay dac biet quan trong vi Giang vien se soat xem ban co tinh du **Accuracy, Precision, Recall, F1-Score va AUC** khong.\n",
    "\n",
    "**Giai thich thuat toan:**\n",
    "- `CrossEntropyLoss` voi `weight`: Nhom ung thu Basal/HER2 rat hiem so voi LumA (Mat can bang du lieu - Imbalance). Tham so `class_weight` giup mo hinh phat nang hon neu doan sai nhom hiem.\n",
    "- `Accumulation_steps = 8`: Vi WSI qua nang, Card T4 Kaggle chi chua duoc Batch Size = 2. De mo phỏng Batch lon = 16, ta tich luy (Cong don) Gradient 8 lan roi moi cap nhat trong so 1 lan.\n",
    "- `CosineAnnealingLR`: Ky thuat giam Learning Rate (Toc do hoc) uon luon theo hinh song Cosine, giup mo hinh \"do xe\" chinh xac vao day diem mu (Global Minima)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(valid_pids) > 0:\n",
    "    # Tinh trong so phat mat can bang class\n",
    "    class_weights = compute_class_weight('balanced', classes=np.unique(labels), y=labels)\n",
    "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "    class_weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)\n",
    "    \n",
    "    # Ham Loss Phan loai, nhung them Label Smoothing (Chong qua tu tin)\n",
    "    criterion = nn.CrossEntropyLoss(weight=class_weights_tensor, label_smoothing=0.1)\n",
    "    \n",
    "    # Chia 5-Fold Cross Validation (Danh gia cheo 5 lan de dam bao tinh khach quan y te)\n",
    "    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
    "    \n",
    "    epochs = 30\n",
    "    batch_size = 2\n",
    "    accumulation_steps = 8\n",
    "    \n",
    "    metrics_list = []\n",
    "    best_global_preds = []\n",
    "    best_global_labels = []\n",
    "    best_global_probs = [] # Dung de ve do thi ROC Curve"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Vong Lap Huan Luyen (Training Loop)\n",
    "Tien hanh huan luyen tren 5 Fold (5 Luot). Chu y qua trinh luu trong so (Save Weights) va in ra 5 chi so cuc xin!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(valid_pids) > 0:\n",
    "    for fold, (train_idx, test_idx) in enumerate(skf.split(valid_pids, labels)):\n",
    "        print(f\"\\n--- BAT DAU FOLD {fold + 1}/5 (BiLSTM + Genomics) ---\")\n",
    "        train_loader = DataLoader(GenomicsDataset([valid_pids[i] for i in train_idx], PT_DIR, rna_500_scaled, label_dict), \n",
    "                                  batch_size=batch_size, shuffle=True, collate_fn=pad_collate)\n",
    "        test_loader = DataLoader(GenomicsDataset([valid_pids[i] for i in test_idx], PT_DIR, rna_500_scaled, label_dict), \n",
    "                                 batch_size=batch_size, shuffle=False, collate_fn=pad_collate)\n",
    "        \n",
    "        model = Multimodal_LSTM_Genomics().to(device)\n",
    "        # Neu co 2 GPU (Dual T4), boc them DataParallel de ep chay da luong\n",
    "        if torch.cuda.device_count() > 1:\n",
    "            model = nn.DataParallel(model)\n",
    "            \n",
    "        # RAdam: Thong minh hon Adam thuong o cac Epoch dau tien\n",
    "        optimizer = optim.RAdam(model.parameters(), lr=5e-4, weight_decay=1e-5)\n",
    "        scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-6)\n",
    "        \n",
    "        best_f1 = 0.0\n",
    "        best_metrics = {}\n",
    "        fold_preds, fold_labels, fold_probs = [], [], []\n",
    "        \n",
    "        for epoch in range(epochs):\n",
    "            model.train()\n",
    "            optimizer.zero_grad()\n",
    "            for step, (img, gen, label, _) in enumerate(train_loader):\n",
    "                logits = model(img.to(device), gen.to(device))\n",
    "                loss = criterion(logits, label.to(device)) / accumulation_steps\n",
    "                loss.backward()\n",
    "                \n",
    "                # Gradient Accumulation\n",
    "                if (step + 1) % accumulation_steps == 0 or (step + 1) == len(train_loader):\n",
    "                    optimizer.step()\n",
    "                    optimizer.zero_grad()\n",
    "            \n",
    "            scheduler.step() # Ep Learning Rate giam theo ham Cosine\n",
    "            \n",
    "            # -------------- DANH GIA (VALIDATION) --------------\n",
    "            model.eval()\n",
    "            preds, tgts, probs_all = [], [], []\n",
    "            with torch.no_grad():\n",
    "                for img, gen, label, _ in test_loader:\n",
    "                    logits = model(img.to(device), gen.to(device))\n",
    "                    probs = torch.softmax(logits, dim=1) # Doi sang Xac suat (0-1) de tinh AUC\n",
    "                    preds.extend(torch.argmax(logits, 1).cpu().numpy())\n",
    "                    tgts.extend(label.numpy())\n",
    "                    probs_all.extend(probs.cpu().numpy())\n",
    "            \n",
    "            val_f1 = f1_score(tgts, preds, average='macro')\n",
    "            # Neu F1 cao hon ky luc cu, thi tinh DU 5 CHI SO va luu Model lai\n",
    "            if val_f1 > best_f1:\n",
    "                best_f1 = val_f1\n",
    "                best_metrics = {\n",
    "                    'acc': accuracy_score(tgts, preds),\n",
    "                    'prec': precision_score(tgts, preds, average='macro', zero_division=0),\n",
    "                    'rec': recall_score(tgts, preds, average='macro', zero_division=0),\n",
    "                    'f1': val_f1,\n",
    "                    'auc': roc_auc_score(tgts, probs_all, multi_class='ovr') # OVR: So tung class voi cac class con lai\n",
    "                }\n",
    "                fold_preds, fold_labels, fold_probs = preds, tgts, probs_all\n",
    "                torch.save(model.state_dict(), f'/kaggle/working/multimodal_lstm_fold{fold+1}.pth')\n",
    "                \n",
    "        # Ket thuc 1 Fold, in ra man hinh\n",
    "        print(f\"[Ket qua Fold {fold+1}] Acc: {best_metrics['acc']:.4f} | Prec: {best_metrics['prec']:.4f} | Rec: {best_metrics['rec']:.4f} | F1: {best_metrics['f1']:.4f} | AUC: {best_metrics['auc']:.4f}\")\n",
    "        metrics_list.append(best_metrics)\n",
    "        best_global_preds.extend(fold_preds)\n",
    "        best_global_labels.extend(fold_labels)\n",
    "        best_global_probs.extend(fold_probs)\n",
    "\n",
    "    print(\"\\n=======================================================\")\n",
    "    print(f\"TONG KET MO HINH MULTIMODAL LSTM (TRUNG BINH 5-FOLD)\")\n",
    "    print(f\"Accuracy  (Do chinh xac) : {np.mean([m['acc'] for m in metrics_list]):.4f}\")\n",
    "    print(f\"Precision (Do chuan xac) : {np.mean([m['prec'] for m in metrics_list]):.4f}\")\n",
    "    print(f\"Recall    (Do bao phu)   : {np.mean([m['rec'] for m in metrics_list]):.4f}\")\n",
    "    print(f\"F1-Score  (Chi so F1)    : {np.mean([m['f1'] for m in metrics_list]):.4f}\")\n",
    "    print(f\"AUC (Area Under Curve)   : {np.mean([m['auc'] for m in metrics_list]):.4f}\")\n",
    "    print(\"=======================================================\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Truc quan hoa Bao cao (Visualizations)\n",
    "Khong mot bai bao cao khoa hoc nao thieu **Confusion Matrix** (Ma tran nham lan) va **ROC Curve** (Duong cong ROC).\n",
    "Doan code duoi day sinh ra 2 bieu do quan trong nay de chung minh mo hinh hoat dong hieu qua."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "if len(valid_pids) > 0:\n",
    "    # 1. VE CONFUSION MATRIX\n",
    "    cm = confusion_matrix(best_global_labels, best_global_preds)\n",
    "    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['LumA', 'LumB', 'Basal', 'HER2'])\n",
    "    fig, ax = plt.subplots(figsize=(8, 6))\n",
    "    disp.plot(cmap='Purples', ax=ax, values_format='d')\n",
    "    plt.title('Ban do Ma tran nham lan - Phan loai Da phuong thuc (LSTM)', fontsize=14, fontweight='bold')\n",
    "    plt.show()\n",
    "\n",
    "    # 2. VE ROC CURVE CHO 4 CLASS (OVR)\n",
    "    # Chuyen nhan (0,1,2,3) thanh One-Hot Encoding de ve ROC cho multiclass\n",
    "    y_test_bin = label_binarize(best_global_labels, classes=[0, 1, 2, 3])\n",
    "    y_score = np.array(best_global_probs)\n",
    "    n_classes = y_test_bin.shape[1]\n",
    "\n",
    "    fpr, tpr, roc_auc = dict(), dict(), dict()\n",
    "    class_names = ['LumA', 'LumB', 'Basal', 'HER2']\n",
    "    colors = ['blue', 'green', 'red', 'purple']\n",
    "\n",
    "    plt.figure(figsize=(10, 8))\n",
    "    for i in range(n_classes):\n",
    "        fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_score[:, i])\n",
    "        roc_auc[i] = auc(fpr[i], tpr[i])\n",
    "        plt.plot(fpr[i], tpr[i], color=colors[i], lw=2, \n",
    "                 label=f'Duong cong ROC nhom {class_names[i]} (AUC = {roc_auc[i]:.3f})')\n",
    "\n",
    "    plt.plot([0, 1], [0, 1], 'k--', lw=2, label='Cham chon ngau nhien')\n",
    "    plt.xlim([0.0, 1.0])\n",
    "    plt.ylim([0.0, 1.05])\n",
    "    plt.xlabel('Ty le Duong tinh Gia (False Positive Rate)', fontsize=12)\n",
    "    plt.ylabel('Ty le Duong tinh That (True Positive Rate)', fontsize=12)\n",
    "    plt.title('Duong cong Dac trung Hoat dong (ROC Curve) - Da phuong thuc LSTM', fontsize=15, fontweight='bold')\n",
    "    plt.legend(loc=\"lower right\")\n",
    "    plt.grid(True, linestyle='--', alpha=0.6)\n",
    "    plt.show()"
   ]
  }
 ]
}

with open(r'C:\Users\huynh\Desktop\breast cancer\06.6_Multimodal_WSI_BiLSTM_Genomics_Train.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook_content, f, indent=1)

print("Da tao file Notebook LSTM huan luyen chi tiet.")
