import json
import os

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Notebook 6.4: GIẢI PHẪU CHI TIẾT CẤU TRÚC ĐA PHƯƠNG THỨC (WSI + GENOMICS)\n",
    "--- \n",
    "## MỤC ĐÍCH CỦA NOTEBOOK NÀY\n",
    "Notebook này **không** được dùng để Training. Nó là một **\"Bản vẽ kỹ thuật\" (Blueprint)** siêu chi tiết, bóc tách từng dòng code, từng Tensor và từng thuật toán trong quy trình Hợp nhất Đa phương thức (Multimodal Late Fusion). \n",
    "\n",
    "Mục đích của nó là giúp bạn **chuẩn bị cho vòng bảo vệ đồ án/luận văn**: thấu hiểu tận gốc rễ những gì mô hình đang làm đằng sau bức màn đen (Blackbox), để tự tin trả lời các câu hỏi phản biện từ Hội đồng chấm thi.\n",
    "\n",
    "### 🔍 Chúng ta sẽ đi qua các phần:\n",
    "1. **Giải phẫu Dữ liệu đầu vào**: Hiểu bản chất File Genomics (500 gen) và File Hình ảnh WSI (.pt)\n",
    "2. **Bí ẩn của Zero-Padding**: Giải quyết bài toán \"kích thước ảnh không đồng đều\" bằng `pad_collate`.\n",
    "3. **Bóc tách Nhánh Thị Giác (Vision Encoder)**: Tại sao lại dùng TransMIL và `[CLS]` token?\n",
    "4. **Bóc tách Nhánh Sinh Học (Genomics Encoder)**: Tại sao dùng MLP, LayerNorm và ép về không gian 512 chiều?\n",
    "5. **Cơ chế Late Fusion (Hợp nhất Trễ)**: Triết lý đằng sau cú `torch.cat` thần thánh.\n",
    "6. **Dummy Forward Pass**: Chạy chay 1 Batch để theo dõi đường đi của Tensor.\n",
    "7. **Phụ lục Q&A**: Bộ câu hỏi \"chống trượt\" bảo vệ đồ án."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib\n",
    "\n",
    "# Cấu hình Font Tiếng Việt quốc dân cho Matplotlib (chống lỗi ô vuông trên Kaggle/Windows)\n",
    "plt.rcParams['font.family'] = 'sans-serif'\n",
    "plt.rcParams['font.sans-serif'] = ['Arial', 'Tahoma', 'DejaVu Sans', 'Liberation Sans']\n",
    "plt.rcParams['axes.unicode_minus'] = False\n",
    "\n",
    "print(\"✓ Đã nạp thành công các thư viện cơ bản.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. GIẢI PHẪU DỮ LIỆU ĐẦU VÀO (INPUT DATA)\n",
    "Mô hình Multimodal yêu cầu 2 đầu vào hoàn toàn khác biệt nhau về mặt không gian vật lý:\n",
    "- **Genomics (Dữ liệu bảng - 1D):** Mức độ biểu hiện (Expression Level) của 500 gen sinh ung thư.\n",
    "- **WSI (Dữ liệu không gian - 2D):** Các bản vá hình ảnh mô học (Patches), đã được trích xuất đặc trưng bởi ResNet50 thành các vector 2048 chiều."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "# ---------------------------------------------------------\n",
    "# 1.1 ĐỌC DỮ LIỆU GENOMICS ĐÃ TIỀN XỬ LÝ TỪ NB 6.0\n",
    "# ---------------------------------------------------------\n",
    "genomics_path = '/kaggle/working/tcga_brca_rna_500_scaled.csv'\n",
    "# Nếu đang test dưới Local, ta có thể sinh dữ liệu ảo (dummy data) để mô phỏng nếu chưa có file CSV.\n",
    "if os.path.exists(genomics_path):\n",
    "    print(f\"Đang đọc file gen tại: {genomics_path}\")\n",
    "    df_gen = pd.read_csv(genomics_path, index_col=0)\n",
    "else:\n",
    "    print(f\"⚠️ Không tìm thấy file thật. Bật chế độ giả lập (Dummy Data) cho 5 bệnh nhân...\")\n",
    "    dummy_pids = ['TCGA-A1-A0SA', 'TCGA-B2-A1G2', 'TCGA-C3-A2H5', 'TCGA-D4-A3I8', 'TCGA-E5-A4J1']\n",
    "    df_gen = pd.DataFrame(np.random.randn(5, 500), index=dummy_pids, columns=[f\"GENE_{i}\" for i in range(1, 501)])\n",
    "\n",
    "print(\"\\n🔍 KHÁM NGHIỆM MA TRẬN GENOMICS:\")\n",
    "print(f\"- Kích thước (Shape): {df_gen.shape} -> [Số lượng Bệnh nhân, Số lượng Gen]\")\n",
    "print(\"- Giải thích: Mỗi bệnh nhân được đại diện bằng một vector 500 chiều (500 con số). Các số này đã được chuẩn hóa Z-Score (Mean=0, Std=1) để tránh việc một vài gen có giá trị bùng nổ (Outliers) lấn át các gen khác.\")\n",
    "display(df_gen.head(3))\n",
    "\n",
    "# ---------------------------------------------------------\n",
    "# 1.2 ĐỌC TENSOR WSI TỪ MỘT BỆNH NHÂN (VÍ DỤ)\n",
    "# ---------------------------------------------------------\n",
    "print(\"\\n🔍 KHÁM NGHIỆM TENSOR ẢNH WSI (Whole Slide Image):\")\n",
    "# Giả lập tensor WSI của 1 bệnh nhân có 850 mảnh (patches)\n",
    "dummy_wsi = torch.randn(850, 2048) \n",
    "print(f\"- Kích thước Tensor WSI: {dummy_wsi.shape} -> [Số lượng Patch, Chiều Đặc trưng]\")\n",
    "print(\"- Cột 850: Nghĩa là tấm tiêu bản của bệnh nhân này được cắt nhỏ thành 850 bức ảnh con (patches).\")\n",
    "print(\"- Cột 2048: Nghĩa là mỗi bức ảnh con đã được nhét qua mạng ResNet50 (pre-trained ImageNet), lấy ở lớp cuối cùng (Flatten Layer) để sinh ra một dãy mã hóa dài 2048 con số.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<div class=\"alert alert-warning\">\n",
    "<strong>Giáo viên hỏi:</strong> <i>\"Tại sao số lượng patch (850) của mỗi bệnh nhân lại khác nhau? Làm sao đưa vào mạng huấn luyện được khi chúng nó lệch chiều?\"</i><br>\n",
    "<strong>Bạn trả lời:</strong> <i>\"Dạ thưa cô/thầy, kích thước khối u của mỗi người là to nhỏ khác nhau, người ung thư nặng mô rải rác nhiều sẽ cắt được hàng ngàn patch, người khối u nhỏ chỉ cắt được vài chục patch. Để huấn luyện theo Batch (nhiều bệnh nhân cùng lúc) trên GPU, ta không thể nối các tensor lệch chiều. Nên em đã dùng kỹ thuật <strong>Zero-Padding (Đệm số 0)</strong> thông qua hàm <code>pad_collate</code> để bù độ dài cho bằng với người có số patch dài nhất trong Batch đó ạ.\"</i>\n",
    "</div>\n",
    "\n",
    "## 2. BÍ ẨN CỦA ZERO-PADDING (`pad_collate`)\n",
    "Hãy xem đoạn code bóc tách quá trình này hoạt động ra sao!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Code mô phỏng pad_collate (Giống hệt code trong hàm collate_fn của DataLoader)\n",
    "def pad_collate_demo(batch_wsi_tensors):\n",
    "    \"\"\"\n",
    "    batch_wsi_tensors: List chứa các tensor WSI của nhiều bệnh nhân trong 1 batch\n",
    "    \"\"\"\n",
    "    # 1. Tìm ra bệnh nhân có nhiều patch nhất trong nhóm (Max Length)\n",
    "    lengths = [tensor.size(0) for tensor in batch_wsi_tensors]\n",
    "    max_len = max(lengths)\n",
    "    \n",
    "    padded_tensors = []\n",
    "    for tensor in batch_wsi_tensors:\n",
    "        pad_size = max_len - tensor.size(0)\n",
    "        # Nếu thiếu bao nhiêu patch, đệm bằng ma trận toàn số 0 (zeros) kích thước [pad_size, 2048]\n",
    "        if pad_size > 0:\n",
    "            zero_padding = torch.zeros(pad_size, 2048)\n",
    "            padded = torch.cat([tensor, zero_padding], dim=0)\n",
    "        else:\n",
    "            padded = tensor\n",
    "        padded_tensors.append(padded)\n",
    "    \n",
    "    # 2. Ghép lại thành 1 Tensor 3D duy nhất để đẩy lên GPU\n",
    "    batch_tensor = torch.stack(padded_tensors, dim=0)\n",
    "    return batch_tensor, lengths\n",
    "\n",
    "# --- TEST THỬ ---\n",
    "patient_A = torch.randn(100, 2048)  # U nhỏ (100 patch)\n",
    "patient_B = torch.randn(450, 2048)  # U to trung bình (450 patch)\n",
    "patient_C = torch.randn(50, 2048)   # U rất nhỏ (50 patch)\n",
    "\n",
    "print(\"Tình trạng Tensor TRƯỚC KHI PAD:\")\n",
    "print(f\"- Bệnh nhân A: {patient_A.shape}\")\n",
    "print(f\"- Bệnh nhân B: {patient_B.shape}\")\n",
    "print(f\"- Bệnh nhân C: {patient_C.shape}\")\n",
    "print(\"-> GPU KHÔNG THỂ HỢP NHẤT (STACK) CHÚNG LẠI!\")\n",
    "\n",
    "batch_tensor, original_lengths = pad_collate_demo([patient_A, patient_B, patient_C])\n",
    "\n",
    "print(\"\\nTình trạng Tensor SAU KHI PAD:\")\n",
    "print(f\"- Kích thước Batch Tensor (GPU Ready): {batch_tensor.shape} -> [Batch_size=3, Max_Patches=450, Dim=2048]\")\n",
    "print(\"-> Bệnh nhân A đã được đệm thêm 350 hàng số 0 ở đuôi.\")\n",
    "print(\"-> Bệnh nhân C đã được đệm thêm 400 hàng số 0 ở đuôi.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. BÓC TÁCH KIẾN TRÚC VISION ENCODER (TransMIL)\n",
    "\n",
    "Đây là thuật toán phân tích Hình học (Morphology) cốt lõi của bài toán. \n",
    "WSI có hàng ngàn bản vá (patches), làm sao mô hình biết nên tập trung vào vùng nào chứa tế bào ung thư? \n",
    "\n",
    "**Cơ chế hoạt động:** \n",
    "1. **Linear Projection:** Ép chiều dữ liệu từ 2048 xuống 512.\n",
    "2. **[CLS] Token:** Chèn thêm 1 vector đặc biệt vào đầu chuỗi. Giống như một \"Người Lớp Trưởng\". Ban đầu nó không biết gì, nhưng qua quá trình Self-Attention (Giao tiếp), nó sẽ \"hỏi han\" hàng ngàn bản vá bên dưới để gom nhặt thông tin xem toàn bộ mô này là ung thư nhóm nào.\n",
    "3. **Transformer Layer:** Bộ não thật sự. Giúp các patch giao tiếp với nhau (Ví dụ patch Mạch máu nói chuyện với patch Tế bào hoại tử kế bên).\n",
    "4. Cuối cùng, ta vứt hết các patch đi, **chỉ giữ lại duy nhất vector [CLS] (kích thước 512)**. Nó chính là kết tinh (Đại diện Tối cao) của cả tấm WSI."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class Vision_Encoder_Demo(nn.Module):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        # 1. Ép chiều: 2048 -> 512 (Để giảm thiểu độ phức tạp và tham số)\n",
    "        self.fc1 = nn.Linear(2048, 512)\n",
    "        \n",
    "        # 2. Khởi tạo [CLS] Token. Tham số nn.Parameter nghĩa là nó có thể học (Learnable) trong lúc train.\n",
    "        self.cls_token = nn.Parameter(torch.randn(1, 1, 512))\n",
    "        \n",
    "        # 3. Lớp Attention ảo (Dùng lớp Transformer_Encoder đơn giản của PyTorch để minh họa)\n",
    "        encoder_layer = nn.TransformerEncoderLayer(d_model=512, nhead=8, dim_feedforward=512, batch_first=True)\n",
    "        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=1)\n",
    "        \n",
    "        # 4. LayerNorm chuẩn hóa cuối cùng\n",
    "        self.norm = nn.LayerNorm(512)\n",
    "\n",
    "    def forward(self, x):\n",
    "        # In ra quá trình biến đổi Shape\n",
    "        print(f\"[Vision] 1. Input WSI Shape : {x.shape} -> [Batch, Patches, 2048]\")\n",
    "        \n",
    "        x = self.fc1(x)\n",
    "        print(f\"[Vision] 2. Sau FC1 (Ép chiều): {x.shape} -> [Batch, Patches, 512]\")\n",
    "        \n",
    "        B = x.shape[0]  # Lấy Batch Size (Số lượng bệnh nhân)\n",
    "        # Nhân bản [CLS] token cho bằng số lượng bệnh nhân trong Batch\n",
    "        cls_tokens = self.cls_token.expand(B, -1, -1) \n",
    "        \n",
    "        # Ghép [CLS] token vào ĐẦU của chuỗi Patches\n",
    "        x = torch.cat((cls_tokens, x), dim=1)\n",
    "        print(f\"[Vision] 3. Sau khi chèn CLS : {x.shape} -> (Patches + 1) -> Vị trí 0 là CLS.\")\n",
    "        \n",
    "        # Chạy qua Transformer (Self-Attention)\n",
    "        x = self.transformer(x)\n",
    "        \n",
    "        # Lấy duy nhất vị trí 0 (Tức là [CLS] token) làm đại diện\n",
    "        cls_out = x[:, 0, :]  \n",
    "        cls_out = self.norm(cls_out)\n",
    "        print(f\"[Vision] 4. Bóc tách [CLS]   : {cls_out.shape} -> [Batch, 512]. ĐÂY LÀ TINH HOA CỦA ẢNH WSI.\")\n",
    "        return cls_out\n",
    "\n",
    "# Chạy thử với Batch WSI lúc nãy\n",
    "vision_model = Vision_Encoder_Demo()\n",
    "vision_features_extracted = vision_model(batch_tensor)\n",
    "print(\"\\n=> Vision Nhánh Đã Hoàn Tất Xử Lý!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. BÓC TÁCH KIẾN TRÚC GENOMICS ENCODER (Tabular MLP)\n",
    "\n",
    "Nhánh Gen có đầu vào siêu đơn giản: Chỉ 500 con số (1D Array). Do đó ta không cần Transformer, chỉ cần mạng MLP (Multi-Layer Perceptron) truyền thống.\n",
    "\n",
    "**Quy trình biến đổi (Forward Pass):**\n",
    "1. `Linear(500, 256)`: Bóp nghẹt thông tin (Bottleneck) để ép mô hình chắt lọc các gen cốt lõi sinh ung thư.\n",
    "2. `LayerNorm(256)`: Chuẩn hóa, kéo phân phối dữ liệu về chuẩn. (Giúp ổn định Gradient). Dùng LayerNorm thay BatchNorm vì BatchNorm sẽ sập nguồn (Crash) nếu `BatchSize = 1 hoặc 2` trong môi trường Đa GPU (DataParallel).\n",
    "3. `LeakyReLU`: Hàm kích hoạt phi tuyến (Non-linear).\n",
    "4. `Dropout(0.3)`: Bắn bỏ ngẫu nhiên 30% nơ-ron để chống Học vẹt (Overfitting).\n",
    "5. `Linear(256, 512)`: Phóng to không gian lên 512 chiều. \n",
    "   - *Tại sao lại là 512?* -> Để bằng đúng với số chiều 512 của ảnh WSI ([CLS] token). Cân bằng Cán cân Quyền lực giữa Hình ảnh và Sinh học khi Hợp nhất!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class Genomics_Encoder_Demo(nn.Module):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        self.net = nn.Sequential(\n",
    "            nn.Linear(500, 256),\n",
    "            nn.LayerNorm(256),\n",
    "            nn.LeakyReLU(0.1),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(256, 512),\n",
    "            nn.LayerNorm(512),\n",
    "            nn.LeakyReLU(0.1)\n",
    "        )\n",
    "        \n",
    "    def forward(self, x):\n",
    "        print(f\"[Genomics] 1. Input Gen Shape : {x.shape} -> [Batch, 500]\")\n",
    "        out = self.net(x)\n",
    "        print(f\"[Genomics] 2. Sau khi qua MLP : {out.shape} -> [Batch, 512]. ĐÂY LÀ TINH HOA CỦA GEN.\")\n",
    "        return out\n",
    "\n",
    "# Sinh dữ liệu Gen giả lập (3 bệnh nhân, 500 gen)\n",
    "batch_gen_tensor = torch.randn(3, 500)\n",
    "\n",
    "gen_model = Genomics_Encoder_Demo()\n",
    "gen_features_extracted = gen_model(batch_gen_tensor)\n",
    "print(\"\\n=> Genomics Nhánh Đã Hoàn Tất Xử Lý!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. LATE FUSION (HỢP NHẤT TRỄ) & PHÂN LOẠI CUỐI (CLASSIFICATION)\n",
    "\n",
    "<div class=\"alert alert-info\">\n",
    "<strong>Giáo viên hỏi:</strong> <i>\"Em gọi đây là Đa phương thức (Multimodal), vậy tại sao em lại dùng Late Fusion (Hợp nhất trễ) ở giai đoạn cuối mà không nhập ma trận Gen vào thẳng ảnh ngay từ ban đầu (Early Fusion)?\"</i><br>\n",
    "<strong>Bạn trả lời:</strong> <i>\"Dạ thưa cô/thầy, Hình ảnh WSI và Hồ sơ Gen biểu hiện (RNA-Seq) tồn tại ở hai không gian hoàn toàn không đồng nhất (Heterogeneous). Hình ảnh là không gian Tọa độ Không gian/Pixel (Spatial), còn Gen là dữ liệu Vô hướng/Phân tử 1D (Molecular). Nếu ghép nối thẳng hàng từ ban đầu (Early Fusion), mạng nơ-ron sẽ bị nhiễu loạn trầm trọng vì không cùng tỷ lệ và bản chất vật lý. Do đó, em phải để 2 nhánh chạy riêng biệt để tự chắt lọc ra Vector ngữ nghĩa bậc cao (512D) của riêng nó, rồi mới nối (Cat) chúng lại với nhau ở phút 89. Kỹ thuật này gọi là <strong>Deep Late Fusion</strong> ạ.\"</i>\n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class Multimodal_LateFusion_Demo(nn.Module):\n",
    "    def __init__(self):\n",
    "        super().__init__()\n",
    "        self.vision = Vision_Encoder_Demo()\n",
    "        self.gen = Genomics_Encoder_Demo()\n",
    "        \n",
    "        # BỘ PHÂN LOẠI CUỐI (CLASSIFIER HEAD)\n",
    "        # Đầu vào = 512 (Vision) + 512 (Gen) = 1024 chiều\n",
    "        # Đầu ra = 4 chiều (Tương ứng xác suất của 4 loại ung thư PAM50: LumA, LumB, Basal, HER2)\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.Linear(1024, 256),\n",
    "            nn.LayerNorm(256),\n",
    "            nn.LeakyReLU(0.1),\n",
    "            nn.Dropout(0.3),\n",
    "            nn.Linear(256, 4) # 4 classes PAM50\n",
    "        )\n",
    "        \n",
    "    def forward(self, wsi, rna):\n",
    "        print(\"=========== BẮT ĐẦU CHU TRÌNH FORWARD PASS ===========\")\n",
    "        v_feat = self.vision(wsi)\n",
    "        g_feat = self.gen(rna)\n",
    "        \n",
    "        print(\"\\n--- TIẾN HÀNH LATE FUSION ---\")\n",
    "        # Dùng torch.cat để NỐI THEO CHIỀU NGANG (dim=1)\n",
    "        fusion = torch.cat((v_feat, g_feat), dim=1)\n",
    "        print(f\"[Fusion] Sau khi torch.cat(vision, gen) : {fusion.shape} -> [Batch, 1024] (512 + 512)\")\n",
    "        \n",
    "        print(\"\\n--- RA QUYẾT ĐỊNH (CLASSIFICATION) ---\")\n",
    "        logits = self.classifier(fusion)\n",
    "        print(f\"[Output] Sau Classifier Head            : {logits.shape} -> [Batch, 4 Classes]\")\n",
    "        \n",
    "        print(\"=========== KẾT THÚC CHU TRÌNH ===========\")\n",
    "        return logits\n",
    "\n",
    "# ---------- THỰC THI (TEST FORWARD PASS) ----------\n",
    "final_model = Multimodal_LateFusion_Demo()\n",
    "\n",
    "# Đẩy dữ liệu Batch 3 bệnh nhân vào Mạng lưới Tối cao\n",
    "predictions = final_model(wsi=batch_tensor, rna=batch_gen_tensor)\n",
    "\n",
    "print(\"\\n🎯 KẾT QUẢ DỰ ĐOÁN THÔ (LOGITS) CHO 3 BỆNH NHÂN:\")\n",
    "print(predictions)\n",
    "\n",
    "# Quy đổi ra Xác suất (%)\n",
    "probabilities = torch.softmax(predictions, dim=1)\n",
    "print(\"\\n🎯 KẾT QUẢ ĐÃ QUY ĐỔI RA XÁC SUẤT (%) CHO 4 NHÓM PAM50:\")\n",
    "print(torch.round(probabilities * 100))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. PHỤ LỤC: BỘ CÂU HỎI \"CHỐNG TRƯỢT\" KHI BẢO VỆ\n",
    "\n",
    "Nếu gặp các Giảng viên chuyên về Toán, Deep Learning hay Y Sinh, đây là những câu \"Trùm cuối\" có thể họ sẽ hỏi. Hãy học thuộc ý chính để trả lời lưu loát!\n",
    "\n",
    "**Q1. Kích thước mô hình của em lớn không? Chạy trên máy thường được không?**\n",
    "> Trả lời: \"Kích thước kiến trúc Late Fusion của em rất nhẹ (chỉ tốn khoảng vài triệu tham số). Nguyên nhân do em KHÔNG dùng ResNet50 để huấn luyện lại từ đầu (End-to-End Image). Em đã sử dụng ResNet50 đóng vai trò Trích xuất đặc trưng ngoại tuyến (Offline Feature Extractor), lưu sẵn ra file `.pt` (Feature Dimension 2048). Quá trình train chính chỉ huấn luyện các lớp MLP, Transformer Attention siêu nhẹ phía sau. Nhờ vậy, ngay cả Card T4 Kaggle cũng có thể chạy mượt mà mà không lo sập vRAM (OOM).\"\n",
    "\n",
    "**Q2. Em có biết cơ chế Attention (Self-Attention) trong nhánh Hình học hoạt động thế nào không?**\n",
    "> Trả lời: \"Self-Attention tính toán sự tương quan (Ma trận Q, K, V) giữa mọi mảnh cắt (patch) với nhau trên toàn bộ bức ảnh. Các bản vá có mô hình khối u tương tự nhau sẽ 'bỏ phiếu' cho nhau một trọng số Attention cao, giúp mô hình bắt được tính bất đồng nhất (Heterogeneity) lan tỏa trên toàn khối u thay vì chỉ nhìn cục bộ như CNN truyền thống.\"\n",
    "\n",
    "**Q3. Có rủi ro nhánh Vision áp đảo hoàn toàn nhánh Gen khiến Gen trở nên vô dụng (Modality Collapse)?**\n",
    "> Trả lời: \"Đó chính là lý do em thiết kế Nhánh Gen và Nhánh WSI CÙNG ÉP VỀ 512 CHIỀU. Nếu nhánh Vision có 2048 chiều mà Gen chỉ có 128 chiều, khi nối lại, gradient sẽ chảy toàn bộ về Vision. Sự cân bằng vector 512-512 ép mô hình phải lắng nghe sinh học và hình ảnh một cách công bằng nhất (Equal Capacity). Sự nhảy vọt F1 lên 0.85 (Nb 6.2) là minh chứng rõ nhất cho việc cả 2 nhánh đều có hiệu lực.\"\n",
    "\n",
    "**Q4. Vì sao lại dùng Variance Threshold (Chọn Top 500) thay vì ném cả 20,500 gen vào mô hình?**\n",
    "> Trả lời: \"Nếu ném cả 20,500 gen, mô hình sẽ dính 'Lời nguyền Số chiều' (Curse of Dimensionality). Hơn 90% số lượng gen trong đó là Gen giữ nhà (Housekeeping genes) hoặc các mảnh rác (Non-coding) biểu hiện giống hệt nhau ở mọi người. Variance Threshold cho phép em lọc ra 500 gen 'điên rồ nhất', dao động dữ dội nhất giữa các nhóm bệnh, đó chính là các Biomarker (Dấu ấn sinh học) thực thụ quyết định kiểu hình của khối u. Càng ít gen, mạng Neural mạng chạy càng nhanh và càng tránh được Overfitting.\""
   ]
  }
 ]
}

with open(r'C:\Users\huynh\Desktop\breast cancer\06.4_Multimodal_Architecture_DeepDive_WSI_Genomics.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook_content, f, indent=1, ensure_ascii=False)

print("Đã tạo thành công Notebook 6.4 siêu chi tiết để phục vụ việc giải thích và bảo vệ đồ án.")
