import json
import os

path = r'C:\Users\huynh\Desktop\breast cancer\05_Classification_TransMIL_SOTA.ipynb'

with open(path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Tìm và thay thế cell huấn luyện (Training Cell)
for cell in nb['cells']:
    if cell['cell_type'] == 'code' and 'class_weights = compute_class_weight' in ''.join(cell.get('source', [])):
        new_source = [
            "if len(valid_pids) > 0:\n",
            "    class_weights = compute_class_weight('balanced', classes=np.unique(labels), y=labels)\n",
            "    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
            "    class_weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)\n",
            "    \n",
            "    # [NÂNG CẤP 1] Thêm Label Smoothing 0.1 để chống Overconfidence\n",
            "    criterion = nn.CrossEntropyLoss(weight=class_weights_tensor, label_smoothing=0.1)\n",
            "    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n",
            "    \n",
            "    epochs = 20\n",
            "    batch_size = 1 # Bắt buộc vì WSI có độ dài biến thiên\n",
            "    # [NÂNG CẤP 2] Gradient Accumulation giả lập Batch Size 16\n",
            "    accumulation_steps = 16 \n",
            "    \n",
            "    fold_results = []\n",
            "    best_global_preds = []\n",
            "    best_global_labels = []\n",
            "\n",
            "    print(f\"Khởi động lò nung SOTA TransMIL (Official + Optimized) trên thiết bị: {device}\")\n",
            "    \n",
            "    for fold, (train_idx, test_idx) in enumerate(skf.split(valid_pids, labels)):\n",
            "        print(f\"\\n--- [TransMIL Official] Bắt đầu Fold {fold + 1}/5 ---\")\n",
            "        \n",
            "        train_pids = [valid_pids[i] for i in train_idx]\n",
            "        test_pids = [valid_pids[i] for i in test_idx]\n",
            "        \n",
            "        train_dataset = MILBagDataset(train_pids, PT_DIR, patient_label_dict)\n",
            "        test_dataset = MILBagDataset(test_pids, PT_DIR, patient_label_dict)\n",
            "        \n",
            "        train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)\n",
            "        test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)\n",
            "        \n",
            "        model = TransMIL(input_dim=2048, n_classes=4).to(device)\n",
            "        # Tăng Learning Rate lên một chút vì đã có Gradient Accumulation\n",
            "        optimizer = optim.Adam(model.parameters(), lr=5e-4, weight_decay=1e-5)\n",
            "        # [NÂNG CẤP 3] Cosine Annealing để tốc độ học lượn sóng mượt mà\n",
            "        scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs, eta_min=1e-6)\n",
            "        \n",
            "        best_f1 = 0.0\n",
            "        best_acc = 0.0\n",
            "        fold_preds = []\n",
            "        fold_labels = []\n",
            "        \n",
            "        for epoch in range(epochs):\n",
            "            model.train()\n",
            "            optimizer.zero_grad() # Xóa gradient đầu epoch\n",
            "            \n",
            "            for step, (features, label, _) in enumerate(train_loader):\n",
            "                features, label = features.to(device), label.to(device)\n",
            "                \n",
            "                logits, _ = model(features)\n",
            "                loss = criterion(logits, label)\n",
            "                # Chia loss cho accumulation_steps để chuẩn hóa gradient\n",
            "                loss = loss / accumulation_steps \n",
            "                loss.backward()\n",
            "                \n",
            "                # Chỉ cập nhật tạ khi tích lũy đủ 16 bước\n",
            "                if (step + 1) % accumulation_steps == 0 or (step + 1) == len(train_loader):\n",
            "                    optimizer.step()\n",
            "                    optimizer.zero_grad()\n",
            "            \n",
            "            # Step scheduler sau mỗi epoch\n",
            "            scheduler.step()\n",
            "            \n",
            "            model.eval()\n",
            "            epoch_preds = []\n",
            "            epoch_labels = []\n",
            "            with torch.no_grad():\n",
            "                for features, label, _ in test_loader:\n",
            "                    features, label = features.to(device), label.to(device)\n",
            "                    logits, _ = model(features)\n",
            "                    _, pred = torch.max(logits, 1)\n",
            "                    epoch_preds.extend(pred.cpu().numpy())\n",
            "                    epoch_labels.extend(label.cpu().numpy())\n",
            "            \n",
            "            val_acc = accuracy_score(epoch_labels, epoch_preds)\n",
            "            val_f1 = f1_score(epoch_labels, epoch_preds, average='macro')\n",
            "            \n",
            "            if val_f1 > best_f1:\n",
            "                best_f1 = val_f1\n",
            "                best_acc = val_acc\n",
            "                fold_preds = epoch_preds\n",
            "                fold_labels = epoch_labels\n",
            "                \n",
            "        print(f\"Fold {fold+1} Kỷ lục mới - Accuracy: {best_acc:.4f} | Macro-F1: {best_f1:.4f}\")\n",
            "        fold_results.append((best_acc, best_f1))\n",
            "        best_global_preds.extend(fold_preds)\n",
            "        best_global_labels.extend(fold_labels)\n",
            "    \n",
            "    mean_acc = np.mean([x[0] for x in fold_results])\n",
            "    std_acc = np.std([x[0] for x in fold_results])\n",
            "    mean_f1 = np.mean([x[1] for x in fold_results])\n",
            "    std_f1 = np.std([x[1] for x in fold_results])\n",
            "    \n",
            "    print(\"\\n=======================================================\")\n",
            "    print(\" TỔNG KẾT TRANSMIL SOTA OFFICIAL (5-FOLD CROSS VALIDATION)\")\n",
            "    print(\"=======================================================\")\n",
            "    print(f\"🎯 Đẳng cấp SOTA: Accuracy: {mean_acc:.4f} ˙ {std_acc:.4f}\")\n",
            "    print(f\"⚖️ Giới hạn đã bị phá vỡ: Macro-F1: {mean_f1:.4f} ˙ {std_f1:.4f}\")\n",
            "    print(\"=======================================================\")"
        ]
        cell['source'] = new_source
        break

with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print("Updated Notebook 5 with Deep Learning Tricks successfully.")
